### ISSUE TITLE
Add Signing Key Management

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#115]
Add the ability to add, list, delete, and associate signing keys with a project.

**Comment by herberzt** [comment]
is this available yet?

**Comment by filmaj** [comment]
@mwbrooks would this apply to both local and remote building?

**Comment by filmaj** [comment]
I verified this this morning that at least for iOS, one can specify the the various [Signing Flags that cordova-ios supports](https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html#using-flags) on the command line via phonegap-cli.

I was able to specify specific provisioning profiles, certificates, and release types without issue via e.g. `phonegap -d build ios --device --buildConfig ~/keys/ios-build-config.json`

Presumably, the same would work for Android: https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#signing-an-app

I am leaning towards closing this issue as I do not believe we need to build a separate feature for this.
