### ISSUE TITLE
[error] {"error":"app not found"}

### ISSUE THREAD

**Issue by gibsosmart** [phonegap/phonegap-cli#122]
When I deleted the app from build.phonegap.com and run the command "phonegap remote build android"

it gives me the following error.

   [error] {"error":"app 482535 not found"}

Looks like there is some dangling instance in the server or on client side which is referring to it.

I tried to restart my machine, logout from cli and try again etc. But of no use.

**Comment by shahrukh4** [comment]
@mwbrooks Thanks, it works and thanks for the help.
