### ISSUE TITLE
Add Public Project Support for PhoneGap/Build

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#124]
## Description

Currently, the remote builds require a private repository because it is a _file upload_ project. If add support for git repositories, then we can support public projects. However, this will require a different workflow.
## Workflow

With git repositories, the project is pulled from the latest source on the git repository. This means a `remote build` command should push the latest code to the repository (dangerous) or warn the user that the latest is not going to be built.

Any ideas?
## Blocked

mwbrooks/node-phonegap-build#42
## Reference

Originally sourced by issue #122.

**Comment by purplecabbage** [comment]
This should be done via a commit hook.  When you commit your code, it triggers the build in pgb via a webhook.
