### ISSUE TITLE
JavaScript API Documentation

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#16]
## Overview

The PhoneGap CLI exposes both a command-line interface and programmatic JavaScript interface.
## Problem

It is tedious and error prone to mirror the function signatures and parameters in the `README.md`.
## Investigate

Investigate generating the documentation to a webpage.

**Comment by filmaj** [comment]
So this one is more about documentation _generation_, yes @mwbrooks ?
