### ISSUE TITLE
PhoneGap CLI doesn't work in terminal

### ISSUE THREAD

**Issue by F481** [phonegap/phonegap-cli#183]
System: Ubuntu 13.04 x64
Installed packages: node, nodejs, npm
Then I installed phonegap via: "sudo npm install -gf phonegap"

After the apparently successful installation I type some phonegap commands in terminal (bash autocomplete works): "phonegap", "phonegap -v" "phonegap help", but there is never a reaction or output on the console:

fabian@fabian-ubuntu:~$ phonegap help
fabian@fabian-ubuntu:~$ 

Also the "phonegap create ..." command doesn't create a new project directory.
I tried to delete all phonegap files and reinstall it, but no changes.

More infos:

fabian@fabian-ubuntu:~$ whereis phonegap
phonegap: /usr/local/bin/phonegap

fabian@fabian-ubuntu:~$ ll /usr/local/bin/phonegap 
lrwxrwxrwx 1 root root 44 Okt  8 18:09 /usr/local/bin/phonegap -> ../lib/node_modules/phonegap/bin/phonegap.js*

**Comment by sivang** [comment]
did all of the above, is still broken. 

sivan@metal:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"


attached also is the install log


[install.txt](https://github.com/phonegap/phonegap-cli/files/497840/install.txt)

if only npm could work ootb like pip ;)
