### ISSUE TITLE
[4.0.0] Add a timestamp to the phonegap CLI output

### ISSUE THREAD

**Issue by mikemike** [phonegap/phonegap-cli#189]
A timestamp will be invaluable to the output of the phonegap CLI.  Currently the output is similar to:

[phonegap] compiling iOS...
[phonegap] successfully compiled iOS app

However, when debugging applications on the device it can often get confusing as to whether or not it has been recompiled, and at what point the last compile took place.  Last modified on the files could be used, but it's not as user friendly as being right there in front of you.

I'll take a look at the source myself and see how easy this would be to implement.

**Comment by purplecabbage** [comment]
Assuming this has been abandoned. Closing.
Please reopen if you still want this feature.
