### ISSUE TITLE
Update Remote Build to Support Merges Directory

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#19]
## Description

Projects are now created using a Cordova project structure (#17).

One feature of the Cordova project structure is the `merges/` directory, which adds support for platform-specific files to replace files in `www/`.

Cordova has a `prepare` command that can be leveraged to preprocess the assets before compiling. We should be able to prepare the assets, before building remotely.

**Comment by filmaj** [comment]
Cordova no longer supports the `merges/` directory - making this issue not applicable. Closing!
