### ISSUE TITLE
Remote Environment Fallback Fails with install command

### ISSUE THREAD

**Issue by lorinbeer** [phonegap/phonegap-cli#202]
example:
on OSX
    $ phonegap install wp7 -- verbose

```
[phonegap] detecting Windows Phone 7 SDK environment...
[phonegap] Checking wp7 requirements...
[phonegap] Running ""/Users/lorin/.cordova/lib/wp/cordova/3.1.0/wp7/bin/check_reqs"" (output to follow)
[phonegap] /bin/sh: /Users/lorin/.cordova/lib/wp/cordova/3.1.0/wp7/bin/check_reqs:      No such file or directory

[phonegap] using the remote environment
[error] missing app data
```

this is specific to the install command. If a local project with the specified platform does not exist, then the attempt to use the remote fallback fails. If a local project with the platform installed does exist, there is no issue.

**Comment by filmaj** [comment]
@mwbrooks the current phonegap docs for the install command, `phonegap help install`, mentions this command is deprecated. Is it worth spending time to fix it, then, or should instead we focus on removing the command?

**Comment by filmaj** [comment]
Ping @surajpindoria

**Comment by surajpindoria** [comment]
Let's close this, as we just discussed removing `phonegap install` command.
