### ISSUE TITLE
phonegap run android and phonegap install android throws error

### ISSUE THREAD

**Issue by doomsbuster** [phonegap/phonegap-cli#220]
I have installed phonegap and cordova via npm commands. However, creating a default project via phonegap create command and building and installing it, i receive the following error:
c:\Temp\phonegap\test>phonegap run android
[phonegap] detecting Android SDK environment...
[phonegap] using the local environment
[phonegap] compiling Android...
[phonegap] successfully compiled Android app
[phonegap] trying to install app onto device
[phonegap] no device was found
[phonegap] trying to install app onto emulator
   [error] An error occurred while emulating/deploying the android project.
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

I receive the same error when I try to run it through cordova emulate command.

My Workstation Specs:
Windows 7
8GB RAM

PATH Variable:
c:\Temp\phonegap\test>echo %PATH%
C:\FAST\JDK64\1.6.0.31.1\bin;C:\FAST\JDK\1.6.0.31\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows
wsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL
ls\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\1E\SMSNomad\;C:\Program Files (x86)\
ram Files (x86)\nodejs\;C:\Users\R097890\AppData\Roaming\npm;C:\Projects-Ashish\Softwares\Android_IDE\sdk\platform-tools
hish\Softwares\Android_IDE\sdk\tools;C:\FAST\eclipse\3.7.2.3\IDE372\ide\plugins\org.apache.ant_1.8.2.v20120109-1030\bin

**Comment by melvin0008** [comment]
any updates?
