### ISSUE TITLE
Device plugin causes '!gap_exec?1390211658809'

### ISSUE THREAD

**Issue by burakson** [phonegap/phonegap-cli#243]
My phonegap version is currently on '3.3.0-0.18.0' and for one of my projects I'm using some plugins. Everything works well unless I include device plugin. 

Reproducing steps:
1-) Create a project (phonegap create gap com.samplegap Gap)
2-) Run on iOS (phonegap run ios)
3-) Add device plugin (phonegap plugin add org.apache.cordova.device)
4-) Build it to compile into platform (phonegap build ios)
5-) Open index.html inside platforms/ios/www and here is the error in console;
"Failed to load resource   file:///!gap_exec?1390211658809"

With this error cordova.js doesn't fire 'deviceready' event, hence nothing seem to work as it should be.

Everything goes back to normal when I do this:
1-) Remove plugin (phonegap plugin remove org.apache.cordova.device)
2-) Build again (phonegap build ios)
3-) No Errors!

I did a bit of research on the web but nothing seem to solve this. Is there something wrong with the set up steps?

**Comment by PiyushL** [comment]
I am experiencing the same issue with inappbrowser plugin....
I thing the steps to reproduce are as follows:

1. Open your index.html in chrome browser.
2. In console you will get the error somewhat like "Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///!gap_exec?1430119897227'."
3.With this error cordova.js doesn't fire 'deviceready' event, hence nothing seem to work as it should be.

I am not able to figure out why is this happening...My iOS hybrid app is running errorfree but when I try to run the same with browser I am stucked with this error...Looking forward to the help...Thanks in advance...
