### ISSUE TITLE
After installing I cannot "phonegap run ios"

### ISSUE THREAD

**Issue by btm1** [phonegap/phonegap-cli#270]
this is how i installed:

phonegap create kontax "com.kontax.app" "kontax"

then from kontax directory

phonegap run ios yields:

[phonegap] detecting iOS SDK environment...
[phonegap] using the local environment
[phonegap] compiling iOS...
[phonegap] successfully compiled iOS app
[phonegap] trying to install app onto device
[phonegap] no device was found
[phonegap] trying to install app onto emulator
   [error] An error occurred while emulating/deploying the ios project. dyld: Library not loaded: @rpath/iPhoneSimulatorRemoteClient.framework/Versions/A/iPhoneSimulatorRemoteClient
  Referenced from: /usr/local/bin/ios-sim
  Reason: image not found
Cordova needs ios-sim version 1.7 or greater, you have version .

my version of osx: 10.9.2
my version of ios sim: Version 7.1 (463.9.41)

**Comment by camilleeyries** [comment]
@pierrem thank :)
