### ISSUE TITLE
Create IPA by default

### ISSUE THREAD

**Issue by klh** [phonegap/phonegap-cli#292]
Add the capability to create an IOS .ipa file (as well as .app) in the build directory...

its as simple as
create a dir called "Payload" 
copy  app_name.app into Payload folder
zip Payload folder
rename folder to app_name.ipa

**Comment by filmaj** [comment]
I don't think this needs additional support to work. I am able to create an IPA by specifying the `--device` flag when running `build ios`. E.g.

`phonegap -d build ios --device --buildConfig ~/keys/ios-build-config.json`

You just need to make sure to pass the [relevant signing flags](https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html#signing-an-app) along - in my example above, I used the `--buildConfig` option to specify all of the various signing flags together.

Closing this issue
