### ISSUE TITLE
Modify phonegap plugin help text to include adding a specific plugin version

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-cli#355]
Related to Issue #354 but pertains to the `phonegap plugin` help text specifically. 

We should update the CLI help text when running the  `$ phonegap plugin` command to include the syntax for specifying a certain plugin version (via the @). Example usage would be nice as well.

Currently the `phonegap plugin` help text shows:

```
Commands:
    add <path>   add a plugin
```

Maybe add something to it like:

```
Commands:
    add <path>              add a plugin      
    add <path>@[version]    add a specific plugin version
```

Also while in there, add example syntax to the examples for the @ sign, as well as with a package name and without the @ sign. I suggest adding:

```
    $ phonegap plugin add org.apache.cordova.camera  
    $ phonegap plugin add org.apache.cordova.camera@0.2.9                                        
```

With the result being:

```
Examples:

    $ phonegap local plugin add /local/path/to/plugin/
    $ phonegap plugin add /local/path/to/plugin/
    $ phonegap plugin add http://example.com/path/to/plugin.git
    $ phonegap plugin add org.apache.cordova.camera  
    $ phonegap plugin add org.apache.cordova.camera@0.2.9                                        
    $ phonegap plugin remove org.apache.cordova.core.geolocation
    $ phonegap plugin list`
```

It appears specifying the @version only works for the `phonegap plugin add` command. I assume since only one can be installed at a time, however I think if they specify a version on remove and the version does match then it should still work. The error given now isn't true. See Issue #356

**Comment by purplecabbage** [comment]
`phonegap plugin help` takes care of this
