### ISSUE TITLE
Support plugin remove@version

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-cli#356]
See Issues #354 and #355 

Currently you can only specify the @version syntax in the `phonegap plugin add` command, not `phonegap plugin remove`. I assume because you can only have one version of a plugin installed, so it's assumed you would just use the general remove command, such as: 

```
   $ phonegap plugin remove org.apache.cordova.camera
```

vs

```
   $ phonegap plugin remove org.apache.cordova.camera@0.2.9 
```

Ultimately both should work though if the user does specify the version and it matches. Currently you get a misleading error. 

For instance, here's how it works currently:

```
$ phonegap plugin add org.apache.cordova.camera@0.2.9
 [phonegap] adding the plugin: org.apache.cordova.camera@0.2.9
 [phonegap] successfully added the plugin
```

If I change my mind about the version and decide to run:

```
$ phonegap plugin remove org.apache.cordova.camera@0.2.9
[phonegap] removing the plugin: org.apache.cordova.camera@0.2.9
{ name: 'CordovaError',
  message: 'Plugin "org.apache.cordova.camera@0.2.9" is not present in the project.     See "plugin list".' }
   [error] Plugin "org.apache.cordova.camera@0.2.9" is not present in the project. See    "plugin list".
```

Though it is definitely present after verifying again and looking at package.json just to make sure... 

```
org.apache.cordova.camera hollyschinsky $ more package.json
{
"version": "0.2.9",
"name": "org.apache.cordova.camera",
"cordova_name": "Camera",
...
}
```

**Comment by torelk** [comment]
if anyone has found a solution to this issue, id be most greatful.

**Comment by filmaj** [comment]
@hollyschinsky did we ever file a Cordova issue for this? I am unable to find it in Apache Cordova's JIRA. If not, I can file it.

**Comment by hollyschinsky** [comment]
@filmaj I don't remember specifically from back then but guessing not if you didn't find it :/

**Comment by filmaj** [comment]
No problem. Filed it in [CB-12678](https://issues.apache.org/jira/browse/CB-12678).

**Comment by purplecabbage** [comment]
Closing in favor of cordova issue, where it makes most sense to fix
