### ISSUE TITLE
phonegap 3.5 error: Uncaught ReferenceError: Media is not defined.

### ISSUE THREAD

**Issue by paulphoenix** [phonegap/phonegap-cli#376]
hello my name is Paul and have this message when i run my android api CLI: Uncaught ReferenceError: Media is not defined. somebody can help my to find a solution for this problem??

**Comment by anjumraheel** [comment]
Thanks! This saved me a lot of time. I recreated my project in a different folder. I forgot to add Media Plugin and my audios stopped working. After adding the plugin everything is all right.
