### ISSUE TITLE
Template Command Spec

### ISSUE THREAD

**Issue by lorinbeer** [phonegap/phonegap-cli#380]
## technical spec of the project template command
spec out the basic syntax and expected behaviour of the template command

### argument to create
    --template <template_arg>
    --recipe <template_arg>
### first order phonegap subcommand
    phonegap recipe <project>

### plugins
- allow plugins to be installed (through plugman/plugin command)
- allow bundles of plugins to be installed

### frameworks
- mutually exclusive

### js only libraries
- wrap as a plugin
- install using templates

**Comment by mwbrooks** [comment]
#46 implemented template support.
