### ISSUE TITLE
specification of template projects ie recipes 

### ISSUE THREAD

**Issue by lorinbeer** [phonegap/phonegap-cli#388]
### How to Specify Recipes

- specify with json

### How would hybrid recipe's work
- pure js lib templates are easy
- framework js lib templates not so much

### What kind of recipes to offer
- cordova recipes, eg plugin collections
- pure js libs, straightforward to do
- js frameworks

### What recipes to offer
- 
-

**Comment by mwbrooks** [comment]
#46 implemented template support.
