### ISSUE TITLE
Can't run on ios - AMDeviceInstallApplication failed

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-cli#426]
I get this error when I try to run the default helloworld project that was created for iOS using using $ phonegap run ios. 

I had added some plugins prior, but the code is not using it, just the default app. I tried to do run before build (which builds anyway and used to work). Trying to do build _after_ run will build but I still can't run with the run command. 

....
[ 49%] Copying /Users/hollyschinsky/MobileProjects/CLITest/platforms/ios/build/device/HelloWorld.app/www/spec.html to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
AMDeviceInstallApplication failed: 0xE8008016: Unknown error.

**Comment by novakben** [comment]
You need to register your COM app id under the apple developer portal and then generate a provisioning profile for your device. Only then you can run on your device. Also make sure the corrospond your app id with the one you've set in your config.xml file.
