### ISSUE TITLE
Add Hooks Support to Remote Commands

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#44]
Hooks are a Cordova-CLI concept that will naturally work with the PhoneGap local commands. However, they do not fire on remote commands.

**Comment by tanansatpal** [comment]
Phonegap is not supporting hooks. Do they plan to do that, or we should just stop using the plugins that uses the hooks for their functionalities.

**Comment by mwbrooks** [comment]
Hi @tanansatpal,

Can you help me better understand what you need to do? Do you need PhoneGap Build to support plugins that use hooks. Or do you have local app hooks that you would like to trigger when using the `remote` commands?

**Comment by filmaj** [comment]
FYI [CB-3460](https://issues.apache.org/jira/browse/CB-3460) is resolved, so that is no longer a blocker for this.

Ping @mwbrooks on this issue. Is it still relevant? Is this something we still want to eventually add / support?

**Comment by filmaj** [comment]
Also ping @surajpindoria :D

**Comment by surajpindoria** [comment]
I believe this is still relevant as PGB does not support hooks, therefore running the CLI command to remote build would also ignore hooks.

**Comment by purplecabbage** [comment]
Build will not support hooks because of security implications.
