### ISSUE TITLE
[4.0.0] phonegap create help - show help doc instead of create a project

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-cli#495]
When you type the help keyword in a CLI command like:

    $ phonegap create help

It would be nice if it could show the help text rather than create a project in a folder called *help* (even though I know that's not what cordova does). I am fairly sure the latest published version does this so we should add support for it back in (and for any other command where that is the case). 

Any extra help the user can easily get is preferred where possible and where it makes sense.

**Comment by mwbrooks** [comment]
Closing. This was added in the 4.0.0 tag.
