### ISSUE TITLE
[4.0.0] Add back ability to specify random order of flags on create

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-cli#496]
Allow the options/flags to be specified in any order on the `$ phonegap create --name --id` rather than assume the order is always --id and --name. 

This is not supported in the cordova CLI, but one would assume it would work that way since you're specifying the actual flag before the value you want it to have and it shouldn't matter which order it's found.  I believe this is also supported in the recent version of the PG CLI currently available as well.

**Comment by mwbrooks** [comment]
Closing. This was added in the 4.0.0 tag.
