### ISSUE TITLE
npm install issue win7 x64

### ISSUE THREAD

**Issue by udithishara** [phonegap/phonegap-cli#502]
I'm Running into this issue when trying to install phonegap, i don't know whats causing it tried re-installing / updating but still no luck, can someone please tell me how to solve this and get it to work 

Node version - v0.10.33
npm version - 1.4.28
System - Windows 7 x64

Here's my console log

Thanks in Advance

```
C:\Users\Udith\Documents\GitHub> npm install -g phonegap
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc3
2-stream
/


> ws@0.4.31 install C:\Users\Udith\AppData\Roaming\npm\node_modules\phonegap\nod
e_modules\connect-phonegap\node_modules\socket.io\node_modules\engine.io\node_mo
dules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-


> ws@0.4.31 install C:\Users\Udith\AppData\Roaming\npm\node_modules\phonegap\nod
e_modules\connect-phonegap\node_modules\socket.io\node_modules\socket.io-client\
node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! ws@0.4.31 install: `(node-gyp rebuild 2> builderror.log) || (exit 0)`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ws@0.4.31 install script.
npm ERR! This is most likely a problem with the ws package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (node-gyp rebuild 2> builderror.log) || (exit 0)
npm ERR! You can get their info via:
npm ERR!     npm owner ls ws
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! cwd C:\Users\Udith\Documents\GitHub
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0
C:\Users\Udith\Documents\GitHub>
```

**Comment by mwbrooks** [comment]
Closing due to no response.

**Comment by Bharat1234** [comment]
Hi I have this following error please help me to solve

C:\>npm install -g phonegap
npm WARN engine cordova-js@3.7.3: wanted: {"node":"~0.10.x"} (current: {"node":"
0.12.0","npm":"2.5.1"})
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node"
:"0.12.0","npm":"2.5.1"})
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc3
2-stream
\


> ws@0.4.31 install C:\Users\BMM\AppData\Roaming\npm\node_modules\phonegap\node_
modules\connect-phonegap\node_modules\socket.io\node_modules\engine.io\node_modu
les\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
C:\Users\BMM\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phon
egap\node_modules\socket.io\node_modules\engine.io\node_modules\ws>node "C:\Prog
ram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\
bin\node-gyp.js" rebuild
|


> ws@0.4.31 install C:\Users\BMM\AppData\Roaming\npm\node_modules\phonegap\node_
modules\connect-phonegap\node_modules\socket.io\node_modules\socket.io-client\no
de_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
C:\Users\BMM\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phon
egap\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io
-client\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\bin\node-
gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.0","npm":"2.5.1"})
C:\Users\BMM\AppData\Roaming\npm\phonegap -> C:\Users\BMM\AppData\Roaming\npm\no
de_modules\phonegap\bin\phonegap.js
phonegap@4.2.0-0.24.2 C:\Users\BMM\AppData\Roaming\npm\node_modules\phonegap
├── colors@0.6.0-1
├── pluralize@0.0.4
├── minimist@0.1.0
├── semver@1.1.0
├── qrcode-terminal@0.9.4
├── shelljs@0.1.4
├── phonegap-build@0.9.1 (colors@0.6.2, qrcode-terminal@0.8.0, shelljs@0.0.9, ph
onegap-build-api@0.3.3, optimist@0.3.7)
├── prompt@0.2.11 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.5, winston@0.6.2,
utile@0.2.1)
├── connect-phonegap@0.14.8 (home-dir@0.1.2, connect-inject@0.3.2, ip@0.3.1, ncp
@0.6.0, findit@2.0.0, shelljs@0.2.6, http-proxy@1.8.1, useragent@2.0.8, request-
progress@0.3.1, localtunnel@1.3.0, connect@2.12.0, archiver@0.10.1, request@2.33
.0, node-static@0.7.0, socket.io@1.0.4, gaze@0.4.3, tar@0.1.19)
└── cordova@4.2.0 (q@1.0.1, underscore@1.7.0, nopt@3.0.1, cordova-lib@4.2.0)

**Comment by mwbrooks** [comment]
@Bharat1234 You may need to install Visual Studio in order to build the node websockets, otherwise try a few workarounds [documented in this Stackoverflow article](http://stackoverflow.com/questions/14278417/cannot-install-node-modules-that-require-compilation-on-windows-7-x64-vs2012).

**Comment by aamir2590** [comment]
![image](https://cloud.githubusercontent.com/assets/12522640/7718655/77a2bf4c-fed1-11e4-9c4c-0b46139582cd.png)

**Comment by aamir2590** [comment]
@mwbrooks  i need your help on this. i'm not getting the solution for the above can you please tell me hoe to fix it

**Comment by aamir2590** [comment]
how*
