### ISSUE TITLE
phonegap run browser on Mac tries to launch app in Windows Chrome in Parallels

### ISSUE THREAD

**Issue by edasque** [phonegap/phonegap-cli#511]
I've not seen this mentioned anywhere. Any idea how to prevent this behavior or what would cause it?

**Comment by mwbrooks** [comment]
Hi @edasque,

I believe the browser is still considered an experimental platform, there are no doubt some major bugs with it.

On my OS X (Yosemite) system, `phonegap run browser` opens properly in a new Chrome window.

Here is a snippet of the logic used by the browser's run script:
```javascript
switch (process.platform) {
  case 'darwin':
    spawn('open', ['-n', '-a', 'Google\ Chrome', '--args', '--disable-web-security', '--user-data-dir=/tmp/temp_chrome_user_data_dir_for_cordova_browser', project]);
    break;
  case 'win32':
    //TODO: Use regex to fix location of chrome.exe
    //TODO: Get --user-data-dir to work for windows
    spawn('C:/Program Files (x86)/Google/Chrome/Application/chrome.exe', ['--user-data-dir="C:/Chromedevsession"', '--disable-web-security', project]);
    break;
}
```

So by the looks of it, it shouldn't open in Parallels unless your Chrome App is somehow associated with Parallels.

To help debug the issue, can you run the following command in your OS X terminal to see whether it opens Chrome in OS X or Parallels:
```
open -n -a "Google Chrome"
```

**Comment by ppkettu** [comment]
open -n -a "Google Chrome" opens Windows Chrome in Parallels, if installed.

To correct that, in Parallels, disable Actions / Options / Applications / "Share Windows applications with Mac".
