### ISSUE TITLE
phonegap remote build all

### ISSUE THREAD

**Issue by nofxx** [phonegap/phonegap-cli#512]
More like semantics, but the remote build doesn't care which platform to build (nor it should).

So what if `phonegap remote build` just works?  

Need to add a platform there `phonegap remote build foo` even if is going to build em all.

**Comment by nofxx** [comment]
Finishing a PR, the API docs:

http://docs.build.phonegap.com/en_US/developer_api_write.md.html#_post_https_build_phonegap_com_api_v1_apps_id_build

**Comment by eirikurn** [comment]
+1 this confused me. E.g. with a CI server, I usually want to build all platforms.
