### ISSUE TITLE
Crash Bug: Clean install of node (latest) and phonegap fails

### ISSUE THREAD

**Issue by klh** [phonegap/phonegap-cli#515]
install fails due to wrong subtree initialization on /use/local/lib/node_modules/phonegap/node_modules/cordova

specifically cordova_lib is not installed in the subtree and causes module.js to throw an error in index.js

     /usr/local/lib/node_modules/phonegap on git:master o [15:48:16]
     $ phonegap
     
     module.js:340
         throw err;
               ^
     Error: Cannot find module '../../node_modules/cordova/node_modules/cordova-lib'
         at Function.Module._resolveFilename (module.js:338:15)
         at Function.Module._load (module.js:280:25)
         at Module.require (module.js:364:17)
         at require (module.js:380:17)
         at Object.<anonymous> (/usr/local/lib/node_modules/phonegap/lib/cordova/index.js:16:26)
         at Module._compile (module.js:456:26)
         at Object.Module._extensions..js (module.js:474:10)
         at Module.load (module.js:356:32)
         at Function.Module._load (module.js:312:12)
         at Module.require (module.js:364:17)

temporary fix:

do `npm install cordova-lib` inside cordova/ to add cordova-lib under node_modules

**Comment by antogerva** [comment]
I have the same issue o windows8 and I did the temporary fix... that did nothing.

**Comment by fgubert** [comment]
same problem here with windows 10. the fix did nothing too.

**Comment by balkantechnologies** [comment]
Did this on ubuntu 15.04, I see cordova-lib under node_modules, yet I still get the same error. Hence the fix doesn't seem to work.

**Comment by mwbrooks** [comment]
I'm having trouble reproducing this issue on Windows 7, 8, 8.1. I've yet to try Windows 10 or Ubuntu.

What version of node.js and npm are you guys using?

```bash
node --version
npm --version
```

Thanks!

**Comment by balkantechnologies** [comment]
I was using node 4.0.0 with the default npm belonging to that version, I don't recall the exact version number. 

Now I'm using node v0.12.7 with npm v2.11.3 and the problem disappeared.

This solved the problem for me on both Ubuntu and on OS/X. The node 4.0.0 installation was a fresh one installed via NVM, yet I got this problem, so I have the impression that this problem might be connected to the nodejs or npm version. As I said: on 0.12.7 it works all fine.

**Comment by pharindoko** [comment]
Hey,

same issue when using phonegap command
```
module.js:338
    throw err;
    ^

Error: Cannot find module '..\..\node_modules\cordova\node_modules\cordova-lib'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Flo\AppData\Roaming\npm\node_modules\phonegap\lib\cordova\index.js:16:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
node --version
v4.1.0
npm --version
2.14.3

unbuild and updated cordova and phonegap npm packages
did not help

**Comment by pharindoko** [comment]
installed phonegap@5.1.1 - now it works again -> bug in new package

**Comment by AdriVanHoudt** [comment]
same here 
npm 3.3.4
node v0.10.40

**Comment by AdriVanHoudt** [comment]
installing 5.1.1 does not even work, in my case probably has to do with new npm version or because of a clean install (global one does not have but I did not re-install that one with the new npm)

**Comment by mwbrooks** [comment]
I'm just working through recreating this bug.

My test scenario is:

```
rm -rf ~/.npm
npm install -g phonegap
phonegap
phonegap create my-app
```

The following environments work:
```
node@0.12.7
npm@2.11.3
---
node@0.12.7
npm@2.14.3  # matching pharindoko npm version
---
node@4.10.0  # official release on nodejs.org
npm@2.14.3  # npm version shipping with latest node
```

The following produces an `npm ERR! code 1` message:

```
node@4.10.0
npm@3.3.3
```

The error is solved by running a cache clean:

```
npm cache clean
npm install -g phonegap
```

At this point, I am able to reproduce the error mentioned above:

```
$ phonegap
module.js:338
    throw err;
    ^

Error: Cannot find module '../../node_modules/cordova/node_modules/cordova-lib'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/phonegap/lib/cordova/index.js:16:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

$ node --version
v4.1.0

$ npm --version
3.3.3
```

**Comment by mwbrooks** [comment]
The error is that the PhoneGap CLI cannot find the `cordova-lib` module. In past version of node, the `node_modules` hierarchy was a straight-forward tree. However, to reduce the excessive directory depth causing pathing issues (especially on Windows), npm has became a little smarter by flatting the node_modules whenever possible. You can [read more about npm flattening under the 'Flat, flat, flat!' release notes](https://github.com/npm/npm/releases/tag/v3.0.0).

**Comment by mwbrooks** [comment]
I've published `phonegap@5.3.2` which should add support for npm@3.x and node@4.x. It also has backwards compatibility for previous version of node and npm.

Thanks for giving me a heads up about this issue! If you continue to have problems, please let me know.

**Comment by VanVan** [comment]
The issue still remain

**Comment by mwbrooks** [comment]
@VanVan thanks for the heads up.

What is your node.js and npm versions?

What is your operating system?

The above error message looks odd: `'....\node_modules\cordova-lib'`. Did you copy & paste it or handwrite it. That path should be generated by node, but it is invalid. It should be: `'..\..\node_modules\cordova-lib'`

**Comment by VanVan** [comment]
@mwbrooks You can find my version below :
```
(Windows7 x64)
{ toonyou: '1.0.0',
  npm: '2.14.3',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '46',
  node: '4.1.0',
  openssl: '1.0.2d',
  uv: '1.7.4',
  v8: '4.5.103.33',
  zlib: '1.2.8' }
```
NB: I edited the cordova path on my last post.

**Comment by AdriVanHoudt** [comment]
Did a clean install and does not work
```
Mac 10.10.5
{ npm: '3.3.3',
  ares: '1.9.0-DEV',
  http_parser: '1.0',
  modules: '11',
  node: '0.10.40',
  openssl: '1.0.1p',
  uv: '0.10.36',
  v8: '3.14.5.9',
  zlib: '1.2.8' }
```
somehow my global install does work...

**Comment by jaryroxas** [comment]
having the same issues
```
▶ phonegap
module.js:338
    throw err;
          ^
Error: Cannot find module '../../node_modules/cordova-lib'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/phonegap/lib/cordova/index.js:23:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

```
node version 0.12.6
npm version 2.14.4
mac osx 10.10.2

**Comment by cocodelacueva** [comment]
I do have the same problem:

module.js:340
    throw err;
          ^
Error: Cannot find module '../../node_modules/cordova-lib'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/phonegap/lib/cordova/index.js:23:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

node -v
v4.0.0

npm --version
2.14.2

:(

**Comment by screendriver** [comment]
Same here

```
Mac OS X 10.10.5
```

```sh
❯ node -v
v2.5.0
```

```sh
❯ npm -v
2.13.2
```

**Comment by jaryroxas** [comment]
i solve it a while ago 
i installed nvm and then installed a new version of node 
node@0.12.7
npm@2.11.3

and reinstalled phonegap

**Comment by AdriVanHoudt** [comment]
@jaryroxas probably the older npm version fixes it

@mwbrooks why not list cordova-lib as a dependency and just require it? (quick thought)

**Comment by cocodelacueva** [comment]
i installed nvm and then installed a new version of node 
node@0.12.7
npm@2.11.3

But i still have the same issue:

$ phonegap create myApp
module.js:338
    throw err;
          ^
Error: Cannot find module '../../node_modules/cordova-lib'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/coco/.nvm/versions/node/v0.12.7/lib/node_modules/phonegap/lib/cordova/index.js:23:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by archy-bold** [comment]
Same issue for me with newly installed versions of Node on Windows 8:
node@4.1.1
npm@2.14.4

I regressed to Phonegap v5.1.1 to get it working:

```
npm remove -g phonegap
npm install -g phonegap@5.1.1
```

**Comment by VanVan** [comment]
To resolve the issue, yes, we can use to phonegap 5.1.1 or use node 0.12.7

The main problem is that Phonegap 5.3.2 doesn't work with node 4.x

Waiting for a Phonegap fix from @mwbrooks :)

**Comment by cocodelacueva** [comment]
I fix it installing cordova instead.

**Comment by mwbrooks** [comment]
For for the info everyone. A few members on my team have also had the issue, which has helped since I've had trouble recreating it on my own system.

Currently, it appears to be caused by nvm and more recent version of npm (>=2.x.x).

@AdriVanHoudt adding `cordova-lib` as a dependency would partially solve the problem. However, the PhoneGap CLI uses the  Cordova CLI to delegate all commands, so including the LIB would double the package size. However, a while ago we added an export to Cordova CLI to expose the LIB, so I can now update our code to use it instead of the path look up. Unfortunately, we also use a private function to list platforms, so I'll need to find a way to continue to support that.

I'm working on a patch that can help. Sorry for the trouble.

**Comment by mwbrooks** [comment]
Hi all,

I've publish an update that should help: `phonegap@5.3.4`:

```
npm install -g phonegap
```

Please install the latest update and let me know how it goes! The issue appears to be related to some recent updates to npm (>= 2.x.x) and nvm. Package dependencies are not longer as predictable, so the PhoneGap CLI cannot easily infer the cordova-lib location. This is okay, since the PhoneGap CLI was breaking the rules :) I believe my latest update should help align everything more cleanly.

If the problem persists, then please try clearing your npm cache and reinstalling:

```
npm cache clean
npm install -g phonegap
```

If the problem persists, please post the following information to help me better recreate the issue:

- node.js version: `node -v`
- npm version: `npm -v`
- Are you using nvm?

**Comment by VanVan** [comment]
@mwbrooks Thank you for the quick fix, it works with npm@2.14.3 and node@4.1.0

**Comment by mwbrooks** [comment]
@VanVan :beers: Thanks for the patience and staying involved in the testing!

**Comment by joseph-roque** [comment]
I was having the issue with `cordova-lib` just a moment ago and this has fixed it for me with npm@2.14.4 and node@4.1.1

**Comment by VanVan** [comment]
@joseph-roque You need to check with phonegap --version that you use version 5.3.4 or do a ```npm install -h phonegap```

**Comment by screendriver** [comment]
Awesome. It's working :+1:

**Comment by AdriVanHoudt** [comment]
did a `rm -rf node_modules` then a `npm clean cache` and then a `npm i` and now I get
 ```bash
/bin/sh: /Users/adri/Projects/.../Project/node_modules/phonegap/node_modules/.bin/cordova: No such file or directory
```

**Comment by mwbrooks** [comment]
@AdriVanHoudt Hmm... now you have me concerned that others are having the same error as you.

Can you try to install it globally rather than locally?

```
npm install -g phonegap
```

You still running `npm 3.3.3` and `node 0.10.x`?

**Comment by AdriVanHoudt** [comment]
yes I am and fear that will break my global install and then I can't continue work :/
I updated to new npm version (should not change anything), and to v5.3.5
Same problem :(

**Comment by mwbrooks** [comment]
Hi @AdriVanHoudt,

I think I'll need a more specific example of how you are installing and using the PhoneGap CLI, if it is not a global installation. Your steps above don't translate to a full use-case because I don't understand what `node_modules` directory you removed and how you are running the PhoneGap CLI locally.

If you note your current global PhoneGap CLI version, then you can always globally downgrade if there is an issue. You may need to use `npm clean cache` if there are issues.

I'll try to look deeper into the way that `phonegap/.bin/cordova` is used to see if I can find an issue.

**Comment by AdriVanHoudt** [comment]
I run 
`phonegap create -d App --copy-from ./build --id 'org.org1.sample' --name 'App' && cd App && phonegap platform add android && phonegap build --debug && phonegap run -d android --device` locally as an npm script
And all my comments are about local use

**Comment by mwbrooks** [comment]
Hey @AdriVanHoudt,

Awesome, thanks for the details. I've been able to recreate your issue and I'm looking into it now.

To recreate the issue, I did:

```
$ mkdir sample-app
$ cd sample-app/
$ npm init .
$ npm install phonegap --save
```

Add the following to `package.json`:

```
"scripts": {
  "android": "phonegap create -d App --id 'org.org1.sample' --name 'App' && cd App && phonegap platform add android && phonegap build --debug && phonegap run -d android --device"
```

```
$ npm run android
...
/bin/sh: /Users/mwbrooks/Development/sandbox/sample-app/node_modules/phonegap/node_modules/.bin/cordova: No such file or directory
...
```

**Comment by mwbrooks** [comment]
@AdriVanHoudt,

Please try updating your local install to use `phonegap@5.3.6` and let me know how it goes!

Cheers,
Michael

**Comment by AdriVanHoudt** [comment]
that works! @mwbrooks thanks for the efforts!

**Comment by mwbrooks** [comment]
Awesome @AdriVanHoudt!

**Comment by cocodelacueva** [comment]
Hello @mwbrooks , I have the same issue when I'm trying to build android. I fix it changing the path: 
instead of export ANDROID_HOME="/home/coco/android-sdk-linux/tools
I put export ANDROID_HOME="/home/coco/android-sdk-linux/
And with this new path I can build the app without erros.
But, now I cannot run the android sdk or avd, because the path is wrong.
My question is, may i put 2 path? How can i do it?

Thanks Bye

**Comment by mwbrooks** [comment]
Hi @cocodelacueva,

You can use both paths to help fix your issue. Here is what my setup looks like on OS X (use your `ANDROID_HOME` on Linux):

```bash
# Android
export ANDROID_HOME=/Applications/android-sdk-macosx/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
```

**Comment by gajraj1990** [comment]
plz prefer me ..which version want used in window 10..
npm and phonegap nd node.js

**Comment by gajraj1990** [comment]
tell me version 
node@?
npm@?
nd 
PhoneGap@?..



currently used =>
node@v5.4.0 x64.msi
npm@3.3.12
and 
when i am installing the PhoneGap Globally Than its occured Error 1 And not installed Propery bcs When we check the Command >>"phonegap create  help " its shows 
error like this ----
---
$ phonegap
module.js:338
    throw err;
    ^

Error: Cannot find module '../../node_modules/cordova/node_modules/cordova-lib'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/phonegap/lib/cordova/index.js:16:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by faluxbkk** [comment]
Had the same problem, last version is working now with phonegap (OSX 10.11.3, phonegap 5.4.1, npm 3.3.12) but any direct cordova command still throws err; (Cannot find module 'cordova-common'). Confusing...
Thanks for your efforts.

**Comment by lambasoft** [comment]
Hello,
I'm having the same error
```
npm -v
1.3.10
```
and
```
node -v
v0.10.25
```

The error I'm receiving:
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'bplist-parser'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:20:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

Thanks

**Comment by devartstudio** [comment]
There is a good solution by erenthegreat here: 
https://forum.ionicframework.com/t/error-cannot-find-module-bplist-parser/38551/4.
Quote:

fixed it by installing missing components manually.

sudo npm install -g bplist-parser
sudo npm install -g minimatch
sudo npm install -g inherits
sudo npm install -g path-is-absolute
sudo npm install -g inflight
sudo npm install -g once

**Comment by ravimallya** [comment]
i also had the same issue. installed missing components one by one manually.

**Comment by aiivon** [comment]
@devartstudio solution -  install missing components manually-  worked for me
