### ISSUE TITLE
Include console plugin by default

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-cli#517]
It would be useful to include the [console plugin](http://plugins.cordova.io/#/package/org.apache.cordova.console) by default when you create a project. This would help a lot not only for convenience but because it's the default in the browser and often trips people up if they don't realize there's a separate plugin needed for that when they start using phonegap/cordova.

**Comment by mwbrooks** [comment]
This is now delegated to the templates that the PhoneGap CLI generates. Closing this issue, since it's out of scope.
