### ISSUE TITLE
Remote build appears to be creating an improperly structured .zip file

### ISSUE THREAD

**Issue by wojobucco** [phonegap/phonegap-cli#518]
Whenever I run the command ```phonegap remote build <platform>```, my application is compressed, uploaded to PhoneGap build, and is built successfully.

However, the application that gets built is not having the contents of its config.xml recognized.  I am suspecting the possible source of the issue is because of the internal structure of the .zip file that is getting created.

I dug into the build/www.zip file that is getting created, and discovered that the full path of my project location on my file system is getting preserved in the .zip file.  So, for example, my www/ directory exists at /home/myuser/Development/my_app/www, and then my www.zip file contains the full /home/myuser/Development/my_app/www path, under which my assets reside.

If I extract the contents from the generated www.zip file, and create a new archive, placing all of my project assets are in the root directory of the .zip, PhoneGap build properly recognizes the config.xml.

I am running Ubuntu 14.04 64-bit, node-js v0.10.25 and using the latest PhoneGap CLI.  I also tried this on PhoneGap CLI 3.6.3 and had the same results.

**Comment by mwbrooks** [comment]
Hi @wojobucco,

I believe this issue has been resolved in the past - but I'm having trouble finding the original issue. I'm going to close this issue but feel free to reopen it.
