### ISSUE TITLE
$ phonegap remote install <platform> should support looking up app ID

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#52]
At the moment, running `$ phonegap remote install android` will fail because it does not have the app data required to lookup the download URL.

**Comment by filmaj** [comment]
I don't have much context for this issue, @mwbrooks. Can you elaborate what the problem / expected result / actual result is?

**Comment by filmaj** [comment]
Ping @surajpindoria too

**Comment by surajpindoria** [comment]
I am able to repro the error, but not really sure what this is meant to do. Maybe the build guys can shed a little more light as to what this command should do.

@wildabeast @goya

**Comment by purplecabbage** [comment]
so that command should :
1. add android to the config
2. (re)upload the app to build
3. wait
which would accomplish the same thing?
