### ISSUE TITLE
Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///!gap_exec?1430122204754'.

### ISSUE THREAD

**Issue by PiyushL** [phonegap/phonegap-cli#530]
I am using phonegap 3.3.0.
I have inappbrowser plugin installed with it...Its the hybrid app developed for the iOS environment.

Now I am trying to open the index.html in chrome browser (as I want to develop the desktop version of the same app using same code), I am getting this error..
"Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///!gap_exec?1430122204754'."

I am not able to figure out the solution to this problem..But somehow I know that this is happening due to this inappbrowser plugin installed in phonegap as window.open() is not working correctly and beacuse of which deviceready function is not getting called.

**Comment by mwbrooks** [comment]
Hi @PiyushL,

If possible, I'd recommend upgrading to the latest version of PhoneGap (3.5.1). However, I understand that some apps need to be locked to a specific version.

Unfortunately, it hasn't been trivial to develop on the desktop browser - although it makes complete sense. We've actually shipped an experimental feature last week to add this support. With the latest version of the PhoneGap CLI, you can develop on your desktop:

```bash
phonegap create my-app
cd my-app/
phonegap serve --browser
# open http://localhost:3000 in your desktop Chrome browser
```

In a future release, it will be enabled by default and not require the `--browser` flag.

Let me know what you think!
