### ISSUE TITLE
can not create phonegap

### ISSUE THREAD

**Issue by veasna234** [phonegap/phonegap-cli#533]
First i am sorry for my bad English.
I am new to phonegap,  just start install to day. 
I have follow this site http://phonegap.com/install/
I started from installing  NodeJS, it is successfully installed.
then I started npm install -g phonegap , it is successfully installed
and in my computer already have Java. I will deploy my app on android.
then I create project phonegap create my-app
but i get this error :
Creating a new cordova project.
Downloading hello-world-template library for www...
Error: getaddrinfo EAI_AGAIN
    at Object.exports._errnoException (util.js:746:11)
    at errnoException (dns.js:49:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
Anyone can help me what i am doing wrong, or my pc miss something

Thank for your help

**Comment by mwbrooks** [comment]
Hi @veasna234,

Thanks for using PhoneGap! I've never seen the error `EAI_AGAIN` but it appears to be a [DNS resolution error](https://github.com/npm/npm/issues/7348#issuecomment-75363630). Trying again may solve the issue.
