### ISSUE TITLE
Whitelist is failure in phonegap 5.0.0-0.28.0

### ISSUE THREAD

**Issue by machalie** [phonegap/phonegap-cli#534]
The android code is used before but now it cannot be run properly in phonegap 5.0.0-0.28.0.  Whitelist is set but it cannot link to the external website.  Local website access has not problem.

**Comment by GC-Mark** [comment]
Same issue here

**Comment by GC-Mark** [comment]
I downgraded `phonegap-cli` to version `4.2.0-0.26.0`, removed the platform and added it again, and `<access origin />` is now working again

**Comment by GC-Mark** [comment]
If your using Cordova 5, you may want to read this http://www.raymondcamden.com/2015/05/25/important-information-about-cordova-5

**Comment by bau720123** [comment]
hi @GC-Mark or @machalie 
have you find any way (unless downgrade) to solve the whitelist problem in latest phonegap cli or phonegap build (build.phonegap.com) ?

**Comment by ashleycoker** [comment]
Has anyone solved this yet?

**Comment by GC-Mark** [comment]
I haven't tired it, but apparently you have to use this plugin now https://github.com/apache/cordova-plugin-whitelist

**Comment by ashleycoker** [comment]
yeah i got that far but my app just has a blank screen now that I have added it in PGB's config.xml - still struggling

**Comment by ashleycoker** [comment]
I should say the app was 'loading' before, it just could not make any XHR requests.  at least thats what I think, as the chrome://inspect debugger cant see the webview like others can.

**Comment by mwbrooks** [comment]
Hello @ashleycoker,

Just a shot in the dark, but I believe the new whitelist plugin requires that you also add a meta tag to your HTML header. Here is [an example of that tag](https://github.com/apache/cordova-app-hello-world/blob/master/www/index.html#L22-L31).

**Comment by mwbrooks** [comment]
Since this issue has been quiet, I hope the whitelist problems have been resolved. We are now running `phonegap@5.3.1`. Feel free to comment/reopen the issue if you are still having problems.
