### ISSUE TITLE
CLI stops live reload after javascrtipt error

### ISSUE THREAD

**Issue by PierBover** [phonegap/phonegap-cli#535]
Whenever I find a JS error the CLI stop autoreloading the project on the iOS device. It detects the file change, but nothing happens after that.

Is this expected behaviour?
Also, why doesn't the CLI show JS errors?

**Comment by filmaj** [comment]
@PierBover are you still having this issue? What kind of JS error are we talking about here? One that happens within your application? Can you describe a way to reproduce the error?

**Comment by PierBover** [comment]
Um that was 2 years ago.

Since I didn't get any response back then (only a bug tag after 3 months) I stopped using Phonegap.

**Comment by filmaj** [comment]
Fair enough. Hoping we can do better moving forward. 

Closing the issue.
