### ISSUE TITLE
CLI throws EMFILE error

### ISSUE THREAD

**Issue by caseypt** [phonegap/phonegap-cli#537]
After upgrading to v5.0.0-0.28.1, `phonegap serve` would throw this error when I connected with a device:

```
[phonegap] starting app server...
[phonegap] listening on 192.168.16.16:3000
[phonegap] 
[phonegap] ctrl-c to stop the server
[phonegap] 

events.js:72
        throw er; // Unhandled 'error' event
              ^

Error: EMFILE, open 'path/to/a/file`
```

I fixed this by following the advice in this [blog post](http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me).

`ulimit -n` returned 1024 originally. I set it to 2560 and I'm now able to connect to the server again without it crashing out.

It might be worth exploring https://www.npmjs.com/package/graceful-fs, as suggested in the linked blog post.

**Comment by mwbrooks** [comment]
Thanks for letting everyone know how to solve this issue @caseypt.

I believe it's related to the `gaze` module that watches for changed files. Depending on your system's available memory and the project size, the error can appear. Sometimes a system reboot solves it, but increasing the `ulimit` is the best option.
