### ISSUE TITLE
emulator not show

### ISSUE THREAD

**Issue by veasna234** [phonegap/phonegap-cli#538]
Hi i am new to phone gap. i have follow the step from installing phone gap until run project
i use this command " phonegap run android --emulator"
but it do not show me the emulator as in document
(http://docs.phonegap.com/en/3.0.0/guide_cli_index.md.html#The%20Command-line%20Interface)
Any know about this problem , please help me .thank
![completed](https://cloud.githubusercontent.com/assets/6067453/8175263/ec2d9684-1411-11e5-8745-979b828cbb56.png)

**Comment by mwbrooks** [comment]
Hi @veasna234,

Can you try running the command `phonegap run android --emulator --verbose` to see additional details on what may be happening?

Cheers,
Michael

**Comment by chenggiant** [comment]
I am trying to run emulator on iOS, also having problem with this command 'cordova run ios --device --verbose' . After I ran, nothing happened and no output at all...
<img width="605" alt="screen shot 2015-10-31 at 16 27 16" src="https://cloud.githubusercontent.com/assets/704843/10862656/4cdff832-7fec-11e5-8469-850719a27370.png">

**Comment by filmaj** [comment]
Looks like an old issue with no updated from the issue reporter. Closing.
