### ISSUE TITLE
Investigate the various debug options

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#539]
A few options that come to mind are:
- Remote Web Inspector
- BrowserSync
- Weinre

**Comment by filmaj** [comment]
Ping @mwbrooks / @surajpindoria for moar context. What's this all about?

**Comment by surajpindoria** [comment]
I think this was around the time we were figuring out how to incorporate the browser platform into `phonegap serve`. How to fake plugin calls, mirror interactions from the device...I'd say close it.

**Comment by filmaj** [comment]
SPRING CLEANING WOO!
