### ISSUE TITLE
PhoneGap Cannot find Zip/Create fix phonegap@2.9.0-0.12.5 fails

### ISSUE THREAD

**Issue by KeyboardMouse** [phonegap/phonegap-cli#544]
Installed Node.Js
npm install -g phonegap
phonegap -version -> 0.9.4
phonegap create i 
phonegap run android

Fail

Tried

npm install phonegap~2.90.0-0.12.5
Run Fail
failed to create the Zip File

**Comment by mwbrooks** [comment]
Hello @KeyboardMouse can you update to the latest version (`phonegap@5.3.1`) and try again? I can reopen the issue if you continue to have a problem.
