### ISSUE TITLE
Unable to build a freshly create project

### ISSUE THREAD

**Issue by realtebo** [phonegap/phonegap-cli#547]
```
FAILURE: Build failed with an exception.




* What went wrong:

Execution failed for task ':processDebugManifest'.

>
Manifest merger failed : uses-sdk:minSdkVersion 7 cannot be smaller than version 10 
declared in library C:\Users\mirko\Phonegap\HelloWorld\platforms\android\build\intermediates
\exploded-aar\android\CordovaLib\unspecified\debug\AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="org.apache.cordova" to force usage
```

I've just done 

    phonegap create HellloWorld
    cd HelloWorld
    phonegap add android
    phonegap build android

No modifications

Probably the template must be updated?

**Comment by jcesarmobile** [comment]
I'm having the same issue

If you set the minSdkVersion to 10 or greater on the config.xml it will work
`<preference name="android-minSdkVersion" value="10" />`

**Comment by macdonst** [comment]
When phonegap-cli pins cordova-android 4.1.0 this bug will be fixed.

**Comment by mwbrooks** [comment]
The `phonegap-cli` now pins `cordova@5.3.1`. So this bug should be resolved.
