### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by AkramSbaih** [phonegap/phonegap-cli#549]
C:\WINDOWS\system32>npm install -g phonegap@latest
npm WARN optional dep failed, continuing form-data@~0.1.0
npm WARN optional dep failed, continuing http-signature@~0.10.0
npm WARN optional dep failed, continuing aws-sign2@~0.5.0
|

> ws@0.4.31 install C:\Users\AKRAM\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
C:\Users\AKRAM\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\socket.io\node_modules\engine.io\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap@latest"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! file C:\Users\AKRAM\AppData\Roaming\npm-cache\read\1.0.7\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\AKRAM\AppData\Roaming\npm-cache\read\1.0.7\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
![a1](https://cloud.githubusercontent.com/assets/9627198/9955114/1cdc22d0-5df7-11e5-95aa-617d0efd5580.PNG)

**Comment by mwbrooks** [comment]
Hi @AkramSbaih,

The PhoneGap CLI uses web sockets for communication. For Windows, this requires compiling the web socket library, which means you need to have Visual Studio installed on your system.

Do you have Visual Studio installed?

A number of people have had issues with this and I'm tempted to rewrite the implementation to not use web sockets. However, currently it is required.

**Comment by mwbrooks** [comment]
Tracked by #573
