### ISSUE TITLE
[Proposal] decouple Cordova and PhoneGap

### ISSUE THREAD

**Issue by stevengill** [phonegap/phonegap-cli#556]
Goal: decouple `cordova` from `phonegap`. `cordova` should be a dependency in the generated `phonegap` projects `package.json` file. When `phonegap` needs to send commands to `cordova`, it should send them to the `cordova` dependency in the projects `node_modules` directory and not the global version. 
## Steps
1. Add `package.json` files to every PhoneGap project. 
   - Use [`init-package-json`](https://www.npmjs.com/package/init-package-json)
   - For new projects, do this during `phonegap create`
   - For existing projects, on `prepare`:
     1. if a `package.json` doesn't exist, add one based on defaults from `config.xml`. Warn users this is happening. 
     2. if a `package.json` does exist, warn users move on to Step 2
2. Add `cordova` as a dependency to `package.json`. Use the existing globally installed version of `cordova` as the version added in package.json. If no globally installed version exists, grab the latest released version from `npm`.
3. Update `phonegap`i to shell out commands to `cordova` dependency instead of globally installed version
## Future Steps
- Update `phonegap` to use `cordova-lib` instead of `cordova`(cli)

Once we come to some consensus on this proposal, I will be closing this issue and transferring this information into a milestone.

Feedback welcomed! Any recommendations on what existing modules I should checkout would also be very helpful!

**Comment by shazron** [comment]
Is doing "Update phonegap to use cordova-lib instead of cordova(cli)" an arduous task? Is the purpose of doing step 3 just to get a release out quickly? (If not I would opt for going cordova-lib directly but not sure how the re-factor etc will affect things).

**Comment by stevengill** [comment]
Not sure how much work it is going to be. I was thinking of speed when I put that task as future instead of  step 3. 

We could run into issues if we wait for a later date to do the refactor to use lib. Mainly some of our `phonega`p users will have `cordova` in their `package.json` and some will have `cordova-lib`. Just adds more headache and confusion. Probably better to include the move to `cordova-lib` part of this proposal

**Comment by mwbrooks** [comment]
For existing projects, on prepare:

@shazron

**Comment by mwbrooks** [comment]
@stevengill 

Thanks for writing up this proposal.

> 1. Add package.json files to every PhoneGap project.
>   - For existing projects, on `prepare`:

I think I'd opt to verify that a `package.json` exists when any PhoneGap command is used, except `help` and `--version`. Before the command can execute, the project should be validated as a node.js project (includes a `package.json`). The CLI already has a utility method to verify that the project is a valid PhoneGap project. We can extend this method to check for `package.json`.

When `package.json` is missing, we should generate it and notify the user.

> Add cordova as a dependency to package.json. Use the existing globally installed version of cordova as the version added in package.json. If no globally installed version exists, grab the latest released version from npm.

Smart transitional phase.

@shazron 

In my experience, the Cordova CLI still handles some critical steps in [creating a project](https://github.com/apache/cordova-cli/blob/master/src/create.js). I think this logic should be moved into `cordova-lib` before we can transition over.

**Comment by stevengill** [comment]
Update: always add the latest version of cordova in package.json.

**Comment by filmaj** [comment]
This is now merged in. Closing.
