### ISSUE TITLE
Outdated install page

### ISSUE THREAD

**Issue by andreyluiz** [phonegap/phonegap-cli#557]
Guys, could you please update [Phonegap Install](http://phonegap.com/install/) page?

It is showing the latest phonegap version as 2.9.1 dated on 05 Nov 2013. It is confusing and it is like the project was abandoned.

Thank you. :)

**Comment by alharding** [comment]
Fixed. Archive area has been removed from the page.

**Comment by mwbrooks** [comment]
Nice, thanks @alharding and thanks @andreyluiz for reporting the outdated content!

**Comment by andreyluiz** [comment]
:+1:
