### ISSUE TITLE
Add support for -webkit-calc()

### ISSUE THREAD

**Issue by auermi** [phonegap/phonegap-cli#559]
Phonegap doesn't support the -webkit- flag for the calc function. It's needed to support calc() on older safari on older devices. http://caniuse.com/#search=calc

**Comment by auermi** [comment]
Just another note. This is needed to support iOS devices running iOS Safari 6.1. Not sure it matters as much on Android.

**Comment by auermi** [comment]
I tried to replicate this issue again and have had no luck. Before it was unable to build. I will post the log if I can replicate this again and let you know what I find.

**Comment by filmaj** [comment]
This is a relatively old issue, and as we march forward, the browsers by default support these features better. At this point, with iOS 9.3+ and Android 5.0+ supporting `calc`, I do not think phonegap or cordova should spend time polyfilling this feature.

If you disagree, feel free to re-open. In the mean time, I'm closing this.
