### ISSUE TITLE
[decouple cordova] Create a new project

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#561]
If we do not ship Cordova, then how will we create a Cordova-compatible project?

**Comment by stevengill** [comment]
Look into breaking out cordova create command from cordova-lib into its own module. Use that as a dependency for phonegap-cli

**Comment by mwbrooks** [comment]
To avoid prompting, we can use a template `package.json` that is updated from `config.xml` values, instead of using `init-package-json`.

**Comment by filmaj** [comment]
Decouple has landed! Closing.
