### ISSUE TITLE
Unfortunately myApp has stopped 

### ISSUE THREAD

**Issue by Majppl** [phonegap/phonegap-cli#562]
Hi I am developing Hybrid Mobile Application. Once i create app and installed .apk file in Mobile it is working fine . But the same .apk file installed in samsung galaxy tab3 it is not working once i scaned barcode automatically app will closed and showing an error alert "Unfortunately myApp has stopped." I am getting this Error repeately . So please help me any to resolve this error on samsung galaxy tab3. Android Version 4.1.2

**Comment by jodiland** [comment]
Hi I am just learning how tp basic program plus im am trying to build my
own wide area network to live in because the usa stole my children and
killed my boyfriend. If I knew how to help you I would.

**Comment by mwbrooks** [comment]
Hi @Majppl,

Your issues sound as though it's related to Android and the Barcode Scanner plugin.

I'd recommend that you ask your question on the PhoneGap Google Groups:
https://groups.google.com/forum/#!topic/phonegap/

Good luck!
Michael
