### ISSUE TITLE
Viewport rendering does not work on Android builds

### ISSUE THREAD

**Issue by auermi** [phonegap/phonegap-cli#563]
You can't scale the viewport on Android devices.
##### For Example

``` html
<meta name="viewport" content="user-scalable=yes, initial-scale=1, maximum-scale=2, minimum-scale=1, target-densitydpi=device-dpi" />
```

**Comment by mwbrooks** [comment]
Can you please try the viewport tag used in the Hello World app:

https://github.com/phonegap/phonegap-app-hello-world/blob/master/www/index.html#L28

**Comment by auermi** [comment]
Hi @mwbrooks thanks for the quick response. So I tried the one you listed and it didn't work. However I used the following and it showed somewhat promising results. Still some issues, but there seems to be at least some scaling here. I'll let you know what I find as I'm still digging.

```html
<meta width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no />
```

**Comment by mwbrooks** [comment]
@auermi, great to hear that you're making progress! Please, keep me updated on how it goes.

Android viewports can be tricky. You may also want to checkout the official [Android Viewport](http://developer.android.com/guide/webapps/targeting.html) guide.

**Comment by auermi** [comment]
Hey @mwbrooks, my major problem seems to be with the version of Android I was initially using to test the device. It seems like anything lower than android 4.4 (Kit Kat) has a lot of issues. I'm guessing that you guys are no longer supporting less than Jellybean since it's so old. However, the viewport tag I linked earlier actually seems to yield better results, but it might just be the way I'm writing my media queries. So if you still plan on supporting below SDK 19 (Android 4.4) then I would think it's worth investigating. If not, we can close the issue.

Thanks again,
Michael Auer

**Comment by filmaj** [comment]
Cordova and PhoneGap now test regularly on Android 4.4 and newer only. As such, closing this issue.
