### ISSUE TITLE
[decouple cordova] Add package.json to existing projects

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#564]
For every PhoneGap project, add a `package.json` file.

For existing projects, add `package.json` on the `prepare` step:
- If a `package.json` doesn't exist, add one based on defaults from config.xml.
  - Warn users this is happening.
- If a `package.json` does exist, do nothing.

**Comment by mwbrooks** [comment]
Always use the latest production `cordova` version rather than trying to resolve the last locally installed phonegap/cordova version.

**Comment by filmaj** [comment]
Decouple has landed! Closing!
