### ISSUE TITLE
Add SQLite-Plugin but can't use

### ISSUE THREAD

**Issue by phuongtailtranminh** [phonegap/phonegap-cli#569]
Hi,

I need some help to use SQLite-Plugin of Chris Brody [https://github.com/litehelpers/Cordova-sqlite-storage]

I'm using PhoneGap version 5.3.9 [phonegap -v]

These following are my commands history:

```
$phonegap create sqlite-demo
$cd sqlite-demo
$phonegap plugin list -> No added plugin
$phonegap plugin add https://github.com/litehelpers/Cordova-sqlite-storage
```

After run plugin add command, I saw the changes in /plugins folder but nothing change in config.xml file, Is that alright?

Then, I'm trying to use demo code, change index.js file:

```
    onDeviceReady: function () {
        app.receivedEvent('deviceready');
        var db = window.sqlitePlugin.openDatabase({ name: "my.db" });

        db.transaction(function (tx) {
            tx.executeSql('DROP TABLE IF EXISTS test_table');
            tx.executeSql('CREATE TABLE IF NOT EXISTS test_table (id integer primary key, data text, data_num integer)');

            // demonstrate PRAGMA:
            db.executeSql("pragma table_info (test_table);", [], function (res) {
                console.log("PRAGMA res: " + JSON.stringify(res));
            });

            tx.executeSql("INSERT INTO test_table (data, data_num) VALUES (?,?)", ["test", 100], function (tx, res) {
                console.log("insertId: " + res.insertId + " -- probably 1");
                console.log("rowsAffected: " + res.rowsAffected + " -- should be 1");

                db.transaction(function (tx) {
                    tx.executeSql("select count(id) as cnt from test_table;", [], function (tx, res) {
                        console.log("res.rows.length: " + res.rows.length + " -- should be 1");
                        console.log("res.rows.item(0).cnt: " + res.rows.item(0).cnt + " -- should be 1");
                    });
                });

            }, function (e) {
                console.log("ERROR: " + e.message);
            });
        });
    },
```

But nothing happen when I start my app. 

Any idea about this problem?

**Comment by GopalKrish** [comment]
First check your plugin folder for sql downloaded from server.
If its present, then open the android.json, ios.json or fetch.json and check weather the plugin added in that file.
Please remember, no change in config file.

**Comment by GopalKrish** [comment]
Did you check with which platform, if its apk file in emulator or device, it will work fine. 
Otherwise if you test using browser, Google Chrome only support the sql plugin.

**Comment by filmaj** [comment]
@phuongtailtranminh first, you'd need to add a platform to your project before your plugin would show up anywhere.

I am closing this issue as it is super old. Please feel free to re-open it if you want to walk through your setup together to see if we can get to the bottom of it.
