### ISSUE TITLE
phonegap serve reload too fast, flag --no-autoreload not work

### ISSUE THREAD

**Issue by tthanh** [phonegap/phonegap-cli#570]
On my computer, phonegap serve reload after 2-5s. I can't see anything happen with my demo app because of reload, jquery append to list and disappear.

OS: Archlinux, Windows 8
Phonegap: 5.4.0 (tried with npm install -g phonegap and npm install -g phonegap@5.4.0)
![screenshot_20160111_230620](https://cloud.githubusercontent.com/assets/8962973/12238790/5476bc84-b8b8-11e5-92a9-a671271db8fb.png)

**Comment by mwbrooks** [comment]
Hi @tthanh,

The terminal output `200 /__api__/autoreload` is a regular ping from the Mobile App to the local server. During that ping, it checks if there are changes that require a reload. Each ping does not necessarily mean that it will reload. Only when you save a file, will it detect a change and force a refresh.

Is your app refreshing every 2s?

**Comment by filmaj** [comment]
Closing as no response from reporter.
