### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by webbjohn** [phonegap/phonegap-cli#577]
I'm banging my head against the wall trying to figure out what path phonegap is looking for and why it can't be found.

I've added JAVA_HOME, ANDROID_HOME, and ANT_HOME to environment variables. I've also added those same paths as well as their bin directories to the path environment variable.

I tried running any phonegap command (create, run, build) with the -d flag but it doesn't tell me anything other than it cannot find the path specified.

If I run `cordova build` or `cordova run` it works just fine.

I'm using phonegap/cordova version 5.4.1.

Any idea what could be causing this? What path is it looking for?

**Comment by mwbrooks** [comment]
Hey @webbjohn,

Sorry to hear that you're running into a problem. Can you provide the full output from your terminal, so that I can better understand the problem?

**Comment by webbjohn** [comment]
Unfortunately, that's pretty much the entire output.

```
[phonegap] executing 'cordova -d build'...
The system cannot find the path specified.
```

**Comment by webbjohn** [comment]
I'm sure this is obvious, but I'm on Windows. Version 8.1.

**Comment by mwbrooks** [comment]
Hey @webbjohn, I've got a Windows 8.1 VM, so I'll give it a shot.

What shell are you using to run the `phonegap` command? For example, _Command Prompt for Node.js_, _Cygwin_, _Msys_, etc.

**Comment by webbjohn** [comment]
I've tried powershell, cmd, and git bash.

**Comment by mehdi1802** [comment]
I am having exact same problem. it was working before but suddenly I am getting "The system cannot find the path specified."
for example this is my output:

cordova platform add browser
Adding browser project...
Running command: cmd "/s /c "C:\Users\{use name}\.cordova\lib\npm_cache\cordova-browser\4.1.0\package\bin\create.bat C:\cordova\test\hello\platforms\browser com.example.hello HelloWorld""
The system cannot find the path specified.
Creating Browser project. Path: platforms\browser
Error: cmd: Command failed with exit code 1

**Comment by surajpindoria** [comment]
Hi @mehdi1802,

What version of the PhoneGap CLI are you using?

**Comment by filmaj** [comment]
@mehdi1802 I would venture to guess that the path in the command mentioned in the output you provided (`C:\Users{use name}.cordova\lib\npm_cache\cordova-browser\4.1.0\package\bin\create.bat`) does not exist.

With the latest phonegap-cli, on Windows 8.1, this worked fine for me:

```
phonegap create test
cd test
phonegap platform add browser
```

If you are still having problems and would like to work through them with me, please re-open the issue and we can work together to get to the bottom of it. In the mean time, I am closing this issue.
