### ISSUE TITLE
Add icon and splash support for local builds

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#58]
### Overview

At the moment, PhoneGap/Build uses `config.xml` to specify the icon and splash screens. However, local builds require the user to manually move icons and splash screens to the appropriate directory under `/platforms/<platforms>`.

### Task

Local builds should support icons and splash screens specified in `config.xml`.

**Comment by JoliPixel** [comment]
+1

**Comment by qkdreyer** [comment]
+1, atm the only alternative is to write a manual script for cp'ing :(

**Comment by mwbrooks** [comment]
Icons and Splashes are now supported by Cordova:
http://cordova.apache.org/docs/en/5.1.1/config_ref_images.md.html#Icons%20and%20Splash%20Screens
