### ISSUE TITLE
Error: Cannot find module 'bplist-parser'

### ISSUE THREAD

**Issue by lambasoft** [phonegap/phonegap-cli#580]
Hello,

After installing phonegap using the following command:
`sudo npm install -g phonegap`

I got the following error when trying to launch:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'bplist-parser'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:20:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

And you should know that:

```
npm -v
1.3.10
```

and

```
node -v
v0.10.25
```

Thanks

**Comment by mwbrooks** [comment]
Hi @lambasoft,

Node `v0.10.25` is quite old. Is it possible for you to upgrade to `v0.12` or newer?

**Comment by lambasoft** [comment]
Hello @mwbrooks,

Alright, I'm noob to this but really would like to learn phonegap.
I couldn't update node for a reason :/ It's always on the same version.

I tried removing then installing again.
Followed this: http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version
and this: http://www.hostingadvice.com/how-to/install-nodejs-ubuntu-14-04/#ubuntu-package-manager

And it's always the same version.

**Comment by Hodes** [comment]
Hello, I had this problem with cordova, but after many tries and read several posts...

I have created my own solution, the main problem was with disconnected cordova reference: 

I complete uninstalled nodejs and npm, also by `apt-get purge npm nodejs` 

I figured out after remove cordova|phonegap stills existed, so `whereis cordova` | `whereis phonegap` has shown where it was, and then I removed it manually. 

After that I installed following https://nodejs.org/en/download/package-manager/

And then https://cordova.apache.org/docs/en/latest/guide/cli/index.html#installing-the-cordova-cli

So, in some cases the current cordova cli or phonegap might be wrong on your /usr/local/bin/... even after uninstall ...

Hope it helps, it is solved for me.

**Comment by filmaj** [comment]
Sounds like things were figured out in here. Closing.
