### ISSUE TITLE
Phonegap create does not include a content security policy in index.html

### ISSUE THREAD

**Issue by michelecos** [phonegap/phonegap-cli#584]
Without a content security policy, like this example

     <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline'; media-src 'self'">

Audio tags will not work and templates will not be loaded from the file system with $.get().
XHR requests will fail in an obscure way and audio tags will just hang displaying loading ...

To reproduce, insert or exclude the sample header above in the head of the index.html file. and insert in the body a tag like this

	<audio controls id="audio">
            <source src="media/test.mp3" type="audio/mpeg">
        </audio>

**Comment by purplecabbage** [comment]
Hi @michelecos 
Is this still an issue? Does [this](https://github.com/phonegap/phonegap-template-hello-world/blob/master/www/index.html#L30) work for you?

**Comment by michelecos** [comment]
I think that this CSP will work. In my context, I had problems with a missing unsafe-eval in default src, but this might be caused by a more complicated running environment, including Babel, webpack, Page.js and jQuery.
It might be a matter of taste adding unsafe-eval to unsafe-inline, relaxing even more the CSP. It is not needed in hello world.

Michele Costabile
michelecos@yahoo.com

**Comment by purplecabbage** [comment]
Yes, if you need a more relaxed policy, you will need to modify the csp yourself.  You should do this anyway so as to only allow what you need.
Thanks for bringing this to our attention!
