### ISSUE TITLE
Disable "Go to app's homepage on a three-finger tap"

### ISSUE THREAD

**Issue by malikolivier** [phonegap/phonegap-cli#585]
I am using `phonegap serve` to test my application.

As it is documented [there](http://phonegap.com/blog/2014/04/23/phonegap-developer-app/#get-to-work), a 3-finger tap will make the browser go to the app's homepage.

That may be useful for some people, but the application I am currently developing is using three or more fingers, causing the app to go back to the homepage whenever I try to do anything.
I could not find any documented way to disable that functionality. Any tip?

Thank you.

**Comment by chrisgriffith** [comment]
Your only real option would be to compile a custom build of the app (it is open source) without that functionality encoded.

**Comment by filmaj** [comment]
This is actually already supported. Check out the help for `phonegap serve`, it mentions options `--no-homepage` and `--no-refresh`.

**Comment by malikolivier** [comment]
It was indeed added in the doc on commit 3c95b5cd1315f046352c3da5adf222262225b738 on Jun 18, 2016. So this solved my issue. Thanks!
