### ISSUE TITLE
Received memory warning and then crash app in ios

### ISSUE THREAD

**Issue by skyblue89** [phonegap/phonegap-cli#587]
Using
phonegap 6.0.3 
ios 9.3 
xcode 7

Rendering a site inside an iframe is causing that my app eventually crash in ios

**Comment by filmaj** [comment]
Closing this issue. We have nothing to go on to reproduce this, and I could not reproduce using latest phonegap-cli and iOS. @skyblue89 if you still are experiencing this issue, please re-open and provide more details as to the reproduction case.
