### ISSUE TITLE
phonegap run fails silently if compilation fails

### ISSUE THREAD

**Issue by wildabeast** [phonegap/phonegap-cli#588]
Edit some of your phonegap iOS app native code to force a compilation failure, then run:

    phonegap run ios

The command will complete and appear to complete successfully, however no app will be installed or run. Running

    phonegap build ios

then shows that compilation fails.

If compilation fails, `phonegap run` should notify as such.

Environment:
    
    phonegap-cli@6.0.3
    Mac OSX 10.10.5
    XCode 7.2.1

**Comment by surajpindoria** [comment]
Tested this using `phonegap@6.0.3` and the issue exists. Using `phonegap@6.2.5` it is no longer reproducible.

Closing issue.
