### ISSUE TITLE
Error: Failed to retrieve phonegap-template-hello-world from NPM.

### ISSUE THREAD

**Issue by karthickv71** [phonegap/phonegap-cli#589]
I cannot create phonegap my-app. i am getting below error how to fix it ..please guide me bro

o

tc@otc-Latitude-E5410:~$ phonegap create app
Creating a new cordova project.

Retrieving phonegap-template-hello-world from NPM...

Error: Failed to retrieve phonegap-template-hello-world from NPM.

**Comment by cfullerton** [comment]
I am having the same issue

**Comment by purplecabbage** [comment]
Is this still an issue? I believe we had a period where things were out of sync, but it should all be good now.

**Comment by karthickv71** [comment]
my network blocked some url and access some sites so i got above issue , i removed security and proxy i solved it..

**Comment by izawad19** [comment]
please help me how can i manage my phonegap project coz i am having the same issue.
best regard

**Comment by izawad19** [comment]
kathckv71 how can you solveed it. plz help me

**Comment by purplecabbage** [comment]
@izawad19 Is this still an issue for you? This seems like it was just a version out of sync issue or a network error.

**Comment by purplecabbage** [comment]
Please reopen if this still affects anyone.

**Comment by karthickv71** [comment]
Hai dude.. i dont know how do i solve this issue... i got above error when creating my project. simply i just remove proxy setting in network..my proxy just blocking retrieve phonegap-template-hello-world from NPM. so i just hide my proxy..then tried..i am successfully created hello-world project..
