### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by feromakovi** [phonegap/phonegap-cli#591]
I've tried to install phonegap via terminal:
`sudo npm install -g phonegap`
Needed versions:
```
node --version
v5.10.1
npm --version
3.8.6
```
So everything looks great, but I've got error:
```
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "phonegap"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! path /usr/local/lib/node_modules/.staging/async-57de1878
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/async-57de1878' -> '/usr/local/lib/node_modules/phonegap/node_modules/localtunnel/node_modules/request/node_modules/form-data/node_modules/async'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/async-57de1878' -> '/usr/local/lib/node_modules/phonegap/node_modules/localtunnel/node_modules/request/node_modules/form-data/node_modules/async'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/feromakovi/npm-debug.log
npm ERR! code 1
```

and npm-debug.log is included.
[npm-debug.txt](https://github.com/phonegap/phonegap-cli/files/214807/npm-debug.txt)

**Comment by surajpindoria** [comment]
Hi @feromakovi,

I was just running into this issue on my machine as well. I managed to get around it by uninstalling first, `npm uninstall -g phonegap`. Can you give this a try and see if it solves anything?

**Comment by feromakovi** [comment]
@surajpindoria very very big thank to you! It helps me a lot and I didn't wonder to uninstall it 👍

**Comment by surajpindoria** [comment]
Usually you don't need to uninstall first, but if you are getting weird errors like that it is a good place to start. Glad it worked! @feromakovi

**Comment by Hamzeh2** [comment]
@surajpindoria 
After almost 2 years,  thank you mate, you literally saved me <3
