### ISSUE TITLE
Windows 8 installation fails

### ISSUE THREAD

**Issue by lordspace** [phonegap/phonegap-cli#594]
`npm install -g phonegap`

Here's the debug
[npm-debug.txt](https://github.com/phonegap/phonegap-cli/files/232927/npm-debug.txt)

Update: this ticket discusses the issue https://github.com/npm/npm/issues/10995

`npm install -g phonegap@latest`

**Comment by surajpindoria** [comment]
Hey @lordspace,

Someone was having a similar issue with this last week as well, #591. They were able to solve this issue by first uninstalling the CLI, `npm uninstall -g phonegap`, and then re-installing. Can you try this and let me know if it works?

**Comment by purplecabbage** [comment]
Are you still having this issue @lordspace ?

**Comment by filmaj** [comment]
Closing due to lack of response from @lordspace. If you still have this issue, please feel free to re-open and provide more information on how to reproduce.
