### ISSUE TITLE
Add Desktop App compatibility

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#595]
The PhoneGap Desktop App is switching from the `connect-phonegap` module to the `phonegap-cli` module. Since Electron has trouble spawning child processes for complex task, we need to test it out and massage any rough areas.
- [PhoneGap Desktop App Milestone](https://github.com/phonegap/phonegap-app-desktop/milestones/0.4.0%20Template%20Support)
- [PhoneGap Desktop App Issue](https://github.com/phonegap/phonegap-app-desktop/issues/631)
- [PhoneGap Desktop App Branch](https://github.com/phonegap/phonegap-app-desktop/tree/template%23631)

**Comment by mwbrooks** [comment]
Currently, the PhoneGap Desktop App fails when creating a project because the Cordova CLI binary cannot be found. @hollyschinsky looked into this and has found that the PhoneGap CLI is looking here:
```
/PhoneGap.app/Contents/Resources/app/node_modules/phonegap/node_modules/.bin/cordova
```
But the binary is located here:
```
PhoneGap.app/Contents/Resources/app/node_modules/phonegap/node_modules/cordova/bin
```

**Comment by filmaj** [comment]
@mwbrooks @surajpindoria @hermwong is this still an issue? The relevant desktop-app bits seem to be resolved.

**Comment by hermwong** [comment]
I think it's closed.
