### ISSUE TITLE
Add telemetry for tracking analytics

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/phonegap-cli#598]
Opt in on first run, additional command to turn on/off at anytime.
Link to privacy policy.

**Comment by purplecabbage** [comment]
Okay, quick poll!
Which makes more sense, is more understandable, and friendliest?

a) `phonegap tracking [on|off]`
b) `phonegap analytics [on|off]`
c) `phonegap telemetry [on|off]`

**Comment by devgeeks** [comment]
+1 for analytics.

tracking sounds creepy and telemetry is vague and might not be understood.

**Comment by GarthDB** [comment]
b.

**Comment by shazron** [comment]
**Tracking**
![cartoon evil](https://cloud.githubusercontent.com/assets/36107/15770749/d413e46c-291a-11e6-95ff-8771f12f8d4b.png)

**Telemetry**
![463533245b1bb502b588758bb98d1dae](https://cloud.githubusercontent.com/assets/36107/15770756/dc338382-291a-11e6-8993-786c68db3cc9.jpg)

**Analytics**  👍 
![35794521-business-people-teamwork-and-planning-concept-smiling-business-team-drawing-chart-on-notice-board-in-stock-photo](https://cloud.githubusercontent.com/assets/36107/15770766/e1d6743e-291a-11e6-8c94-b753acde6253.jpg)

**Comment by hermwong** [comment]
I vote B.

**Comment by purplecabbage** [comment]
Thanks all!
Voting is now closed.  Going with 

![](https://cloud.githubusercontent.com/assets/36107/15770766/e1d6743e-291a-11e6-8c94-b753acde6253.jpg)

**Comment by purplecabbage** [comment]
This is done to my satisfaction. Please merge #604 if you agree.
NodeVersion is tracked, as is OS and app version.

![screen shot 2016-06-15 at 2 45 59 pm](https://cloud.githubusercontent.com/assets/46134/16098527/5e2e4344-3308-11e6-95b7-914f622286ba.png)

**Comment by mwbrooks** [comment]
Looks great!
