### ISSUE TITLE
npm install -g phonegap@latest never ending download

### ISSUE THREAD

**Issue by shofwan** [phonegap/phonegap-cli#605]
Why it's keep downloading?  it's already exceed 150MB! meanwhile the source is only 100KB.
Then I stopped it before it draining my internet's kuota.
Please help.

I'm Using windows 8.1 Pro
64 bit,
this is the first nodeJS that I install (never install other from npm). 
![image](https://cloud.githubusercontent.com/assets/5621504/15918559/1505cd02-2e32-11e6-8481-d341d5ac1a24.png)

**Comment by shofwan** [comment]
Additional info:
![image](https://cloud.githubusercontent.com/assets/5621504/15918620/d4450cb4-2e32-11e6-9709-1a0dc099b464.png)

**Comment by mwbrooks** [comment]
Hi @shofwan,

It looks like you are running everything correctly. `npm install -g phonegap@latest` will also install all of PhoneGap's npm dependencies (declared in `package.json`). This is typically ~100MB, so it's unfortunate about your bandwidth but there is no way around it.

The latest version of npm (`npm@3.x`) tries to reuse npm modules shared between packages. This could reduce the amount that you need to download.

@devgeeks mentioned to me that `npm@2.x` installs uses 112MB to install PhoneGap, while `npm@3.x` uses 95MB.

**Comment by shofwan** [comment]
Is the latest version can be found here? [latest](https://nodejs.org/en/download/).
according to that it's npm@4.4.5 right?

**Comment by shofwan** [comment]
![image](https://cloud.githubusercontent.com/assets/5621504/15949641/43310c36-2ed3-11e6-838c-1658a3ec0641.png)
Okay actually my npm is still 2.15.5.
Where can I found npm@3.xx ?

**Comment by shofwan** [comment]
Ok I found [it](https://github.com/npm/npm/releases/tag/v3.9.5). Thank you.

**Comment by shofwan** [comment]
The problem persists.
Phonegap installs with no ends. Then I try to copy phonegap files manually from my friends computer into my node_modules directory. And then this happen:
![capture](https://cloud.githubusercontent.com/assets/5621504/15956071/29c91d8c-2f10-11e6-9f95-e1d93007ecfd.JPG)

Could this be the root cause of the problem?
My npm's path: C:\Users\Lenovo\AppData\Roaming\npm\node_modules
