### ISSUE TITLE
Build ios with characters

### ISSUE THREAD

**Issue by julio6114** [phonegap/phonegap-cli#608]
Hi everybody,

I've create a project that appname is "Bien déjeuner".
When I try to build on ios I've got this error : 

`xcodebuild: error: The project 'Bien Déjeuner.xcodeproj' does not contain a target named 'Bien Déjeuner'.`

It seems it's the "é" character it block build.

Thanks for your answers

**Comment by surajpindoria** [comment]
Hi @julio6114,

This is a known issue with PhoneGap / Cordova and we are currently working on a fix. In the meantime, you can continue testing your iOS project by opening it in Xcode, `open platforms/ios/Bien Déjeuner.xcodeproj` and building from there.

**Comment by surajpindoria** [comment]
Cordova issue for referenece: https://issues.apache.org/jira/browse/CB-11401

**Comment by shazron** [comment]
Unfortunately the workaround -- for now -- is to not use any accented characters in your project name. I know that is not what you want to hear. I'm trying to find the root of the problem and fix.

**Comment by julio6114** [comment]
Ok thanks a lot! I would follow the issue closely ;)

 I use an other solution. I've created a hook before_build which parse and update *-Info.plist in order to change the CFBundleDisplayName propery

**Comment by shazron** [comment]
It appears I found a fix (see the Cordova issue). Should be in the next platform release (not this upcoming one, but the next).

**Comment by shazron** [comment]
Update: turns out this is will be fixed with the upcoming cordova-ios 4.2.0 release probably later this week.

**Comment by surajpindoria** [comment]
Hey @julio6114,

cordova-ios@4.2.0 has been released with a fix for this. If you run `phonegap platform update ios@4.2.0` you will able to run all commands as expected!

**Comment by julio6114** [comment]
Thanks you very much!
