### ISSUE TITLE
Feature request: phonegap serve auth or IP restriction

### ISSUE THREAD

**Issue by brandonros** [phonegap/phonegap-cli#611]
I'd have nginx do the auth, but by default, it binds to all IPs.

**Comment by mwbrooks** [comment]
@brandonros interesting suggestion. Are you hosting `phonegap serve` as a public web server? Is that why you would like to restrict who can access it?

**Comment by brandonros** [comment]
@mwbrooks Something like this. I spun it up on a DigitalOcean droplet, which is publically exposed. I'd hate for what I'm doing to get sniffed out, especially with their "known" IP range. It isn't crucially sensitive (or else I wouldn't do it), but I thought it'd be a cool feature.

I thought about an nginx proxy_pass with HTTP auth handled there, but I take it that the client/server combination aren't straight and pure HTTP? Is there a special protocol?

**Comment by filmaj** [comment]
Putting nginx in front of `phonegap serve` may work - my one concern would be to ensure websockets are handled properly.

I'm not sure what the feature request here is - enabling some manner of authentication for phonegap serve, or not binding to all IPs? Or both?

I don't think building auth into the `phonegap serve` makes sense - its main purpose is local development and interoperability with the PhoneGap Developer App. The use case there is relatively narrow and well defined, and I don't think it is worth expanding beyond that.

That said, regarding binding-to-IP, that should be easy to implement and I see no issue with providing an option for specifying that.

Any further information you can provide, @brandonros, would be helpful!

**Comment by purplecabbage** [comment]
localtunnel is there and can do some of this.
Otherwise, please send a pr if you have done some work towards this.
