### ISSUE TITLE
Windows Phonegap keeps crashing on file changes

### ISSUE THREAD

**Issue by stimpy23** [phonegap/phonegap-cli#622]
Hi everybody,
Since a few weeks, my PhoneGap keeps crashing every second time, I change any file of the served project.
Doesn't matter whether I'm using the CLI-Version installed via npm or the desktop client, but only happens on my windows system. MacOS is fine, though...
I already read about antivirus-software blocking access to changed files while scanning, but excluding the phonegap-project-directory from live-scanning didn't change anything.
The Desktop-App turns black, the cli-version just stops doing anything. After restarting everything's fine again..
I'm on Windows 10, my anti-virus is Avira Pro, my IDE is NetBeans and I don't have any debug-logs for posting.. :/
Cheers,
Philipp

**Comment by surajpindoria** [comment]
Hi @stimpy23,

What version of PhoneGap are you using?

**Comment by stimpy23** [comment]
Hi surajpindoria,

I tried it with v0.3.3 and 0.3.2..

**Comment by surajpindoria** [comment]
And what versions of the CLI are you using?

**Comment by stimpy23** [comment]
Sorry for the delay.. ..My computer crashed on monday and I had to reinstall everything, including windows..
Yesterday, I tested phonegap-cli and -desktop and both seem to work, well, better now..
The cli-client (v6.2.9) still crashes sometimes saying an existing file doesn't exist, but it doesn't freeze anymore. (Antivirus was disabled...)
The Desktop-Client (v0.3.3) didn't even crash so far, but I haven't been using it a lot, yet..
I'd say: We can close this for now and I'll come back when this happens again...
Thanks anyway for your help!

**Comment by surajpindoria** [comment]
Ok, closing for now. If this comes up again please feel free to reopen the issue.
@stimpy23
