### ISSUE TITLE
ngcordova $cordovaBarcodeScanner

### ISSUE THREAD

**Issue by georgezams** [phonegap/phonegap-cli#623]
When i run phonegap serve and go to test the barcode scanner it does not work? Using the latest release of phoneGap 6.3.0 and cordova 6.2.0, any help would be appreciated!

**Comment by chrisgriffith** [comment]
Using phonegap serve to test your app within the PhoneGap Developer App on your device means you are only able to use the plugins that it has installed. Any additional plugins like the Barcode Scanner will not be recoginzed. You will need to compile to app and deploy it in a standard fashion.

**Comment by georgezams** [comment]
Thank You, just saved me more hours of reading 👍

**Comment by surajpindoria** [comment]
Here is a link to the Developer App docs on how to create a custom build.

https://github.com/phonegap/phonegap-app-developer#adding-custom-plugins

**Comment by georgezams** [comment]
Thank You!
