### ISSUE TITLE
Don't run update check if the CLI is invoked as a child process from PhoneGap Desktop

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-cli#624]
We should add a check to see if the `ELECTRON_RUN_AS_NODE` flag is set and avoid running the `updateCheck` code that checks for an updated CLI. Currently this update code is executed every time in [cli.js](https://github.com/phonegap/phonegap-cli/blob/3552464baec3b7142b6ad296791e5cfe1cf3ab97/lib/cli.js#L51).

**Comment by mwbrooks** [comment]
Instead, I think we should support a `--update-check` and `--no-update-check` flag and programmatic option. This will allow the Desktop app to disable update checks in the same way that it disables analytics.

**Comment by surajpindoria** [comment]
This might be a better way to go so that we can give people a way to save their opt-out status. Currently you can use `--no-update-notifier` but this only works on a per command basis and will still go through some of the update code that might cause us some issues in the desktop app.

**Comment by filmaj** [comment]
I believe this is now [resolved in latest master](https://github.com/phonegap/phonegap-cli/blob/master/lib/cli.js#L50-L55) - we check for the Electron env variable. Closing.
