### ISSUE TITLE
Update template object in package.json for PG-Desktop Template support

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-cli#641]
The PhoneGap Desktop needs a few small changes to the template object in `package.json`.

1. add an index to template so that we can set a display / sort order of the templates in the Desktop App.
1. update the template descriptions to match the copy seen in the following up [mockup](https://cloud.githubusercontent.com/assets/178345/17635266/41e34238-608b-11e6-8240-14898e89c321.png) (right image).
1. add a name property so that the Desktop app can display a user friendly name for each template

**Comment by hermwong** [comment]
Example of changes to template object in `package.json`

```
    "hello-world": {
      "index":"0",
      "name":"Hello World",
      "description": "A very simple app, built on top of the blank template.",
      "npm": "phonegap-template-hello-world"
    }
```

**Comment by hermwong** [comment]
Another solution which would require less manual updating of template index would be to store the templates in an array in `package.json`.

```
template: [
  {
    name: "Hello World",
    description: "A very simple app, built on top of the blank template.",
    npm: "phonegap-template-hello-world"
  },
 {
    name: "Snotify",
    description: "A full example app with words to add to the description.",
    npm: "phonegap-template-snotify"   
 }
]
```

**Comment by purplecabbage** [comment]
+1 to an array, but call it 'templates'

name and description are duplicate info from the package.json of the actual template, so I would worry about out of sync info. 

In prep for search I would default the ui for an empty description and make name be the id (npm) if name is empty. 

Versioning is also important, maybe it should be 
npm: pg-template-snotify@1.3.0 so you always get a known to work template for ones that we recommend.

**Comment by hermwong** [comment]
Yeah, currently we don't use any version pinning for templates. This has caused issues for us in the past when a template has changed and the newest version of that template wasn't compatible with the Desktop App.

**Comment by hermwong** [comment]
[`getTemplateInfo`](https://github.com/phonegap/phonegap-cli/blob/master/lib/phonegap/create.js#L195) method will need to be changed to accommodate the new JSON structure for templates.

[`addTemplates`](https://github.com/phonegap/phonegap-app-desktop/blob/template/www/js/templates.js#L20) method also needs to be modified to parse the new JSON structure for templates.
