### ISSUE TITLE
Retrieving phonegap-template-hello-world using npm

### ISSUE THREAD

**Issue by makondemwale** [phonegap/phonegap-cli#645]
C:\myapplication>phonegap create helloworld
Creating a new cordova project.
Retrieving phonegap-template-hello-world using npm...
C:\myapplication>

**Comment by devgeeks** [comment]
Not sure what your issue is as the hello world template is supposed to be fetched using npm when creating a new project.

Can you clarify what is not working as expected?

Is it not fetching the template and creating the app?

**Comment by makondemwale** [comment]
Morning,

Creating the app is the one which is not working, have note that the folder
will be created but certain folder called cordova  is  not there from the
folder. The below are the screen short of the command and the folder
created .

[image: Inline image 1]


C:\helloword>phonegap create helloworld

Creating a new cordova project.

how should be successfully message  look like.


thanks

**Comment by devgeeks** [comment]
@makondemwale I am not seeing the image, but this is what a basic hello world app folder structure should look like:

![helloworld2](https://cloud.githubusercontent.com/assets/554999/18259945/ecb8eba4-742c-11e6-866e-79b42756ee0a.png)

**Comment by makondemwale** [comment]
Morning,

OK, after project is created I cant  see the folder called Cordova in my
project folder. if Cordova  folder is not there is it not problem ??


On Sep 6, 2016 4:25 AM, "tommy-carlos williams" <notifications@github.com>
wrote:
>
> @makondemwale I am not seeing the image, but this is what a basic hello
world app folder structure should look like:

**Comment by surajpindoria** [comment]
There should not be a folder called `Cordova`. The directory structure shown above is what you should see once you add this template.

**Comment by devgeeks** [comment]
There used to be a hidden folder called `.cordova` once upon a time, but it has been phased out.

**Comment by filmaj** [comment]
Looks like there is no actual issue in here. Closing.
