### ISSUE TITLE
PhoneGap CLI doesn't work in terminal

### ISSUE THREAD

**Issue by sivang** [phonegap/phonegap-cli#648]
sivan@metal:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

[install.txt](https://github.com/phonegap/phonegap-cli/files/497841/install.txt)

**Comment by surajpindoria** [comment]
What version of node and npm are you using? Also are there any errors either from the installation or when you try to run a `phonegap`

**Comment by filmaj** [comment]
@sivang you will need to provide more info in order for us to help you with your issue. The `install.txt` file you uploaded looks fine to me - ends in an zero exit code with no errors.

If you are still having issues, feel free to re-open this issue thread. In the mean time, I am closing this.
