### ISSUE TITLE
Case Sensitive issue for Phonegap Build

### ISSUE THREAD

**Issue by riteshe63** [phonegap/phonegap-cli#649]
I have two images of similar names just having a differentiation of case letter, for example, `Name.jpg` and `name.jpg`. Phonegap does not support this and throws an error everytime the app build process fails.

**Comment by surajpindoria** [comment]
Are both of the files in the same directory? And what is the error that you are seeing?

**Comment by riteshe63** [comment]
Yes both of the files in same directory. And **Error is**

:processArmv7DebugResources
 FAILED


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugResources'.

**Comment by riteshe63** [comment]
Yes, Mac and Windows do not allow to have two files with the same name for different cases. And if we rename one of the file then it works fine.
I am using Ubuntu OS and Ubuntu is case sensitive, So in this case it shows error, Phonegap tool is one of the best successful tools for mobile app build. So if possible, please try to add this feature so as to bring improvement in the tool.

**Comment by surajpindoria** [comment]
Unfortunately since the case sensitivity comes down the OS there isn't much we can do to add support for filenames like this. But we can certainly look into throwing an error/warning when we detect this.

Thanks for bring this to our attention @riteshe63!

**Comment by riteshe63** [comment]
@surajpindoria Thanks for your response. Yes this is an OS issue but we really struggled and literally took weeks to debug this issue because of the generic error message.

I don't have much experience with the code in this repo. Incase you can give me some hints as to how to do this PR, I can try to contribute.

Also, we are currently raising this issue as part of https://github.com/rcorp/standard-project-structure, do have a look and give your feedback.

**Comment by filmaj** [comment]
I'm not sure what more we can do here. This is more to do with how Android packages assets up than anything else. I think one could get more info about what specifically failed during Android packaging by providing the flag ` -- --gradleArg=--info`, i.e. `phonegap build android -- --gradleArg=--info`.

Closing this issue for now, if you feel there is more work to be done here, and have a suggestion on how we could go about fixing or improving this, feel free to re-open to re-initiate the conversation.
