### ISSUE TITLE
sudo npm install -g phonegap@latest failed

### ISSUE THREAD

**Issue by edward9145** [phonegap/phonegap-cli#654]
### PhoneGap CLI, node & npm versions
Mac OS 10.11.6
phonegap-cli 6.3.0
node v6.9.1
npm 3.10.8

### Expected Behaviour
phonegap should be installed successfully

### Actual Behaviour
npm ERR!

### Steps to Reproduce 
I installed the phonegap-cli before, 
but after I updated the npm and node, 
command link lost, `-bash: phonegap: command not found`
So I try to use npm install phonegap again 

#### Sample Code that illustrates the problem

[npm-debug.log.zip](https://github.com/phonegap/phonegap-cli/files/541553/npm-debug.log.zip)

#### Error messages
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "phonegap@latest"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /usr/local/lib/node_modules/.staging/ansi-cdab0442
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-cdab0442' -> '/usr/local/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-cdab0442' -> '/usr/local/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kejiawu/npm-debug.log
npm ERR! code 1

```

**Comment by surajpindoria** [comment]
Hi @edward9145,

Some other users have seen this before. If you could try uninstalling first, `npm uninstall -g phonegap`, and then reinstalling, `npm install -g phonegap`, others have found that this helps.

**Comment by edward9145** [comment]
It works now, thanks for the help!
