### ISSUE TITLE
Debug Mode issue in phonegap cli - 6.3.0 for ios

### ISSUE THREAD

**Issue by mobileias** [phonegap/phonegap-cli#656]
### PhoneGap CLI, node & npm versions
`<preference name="phonegap-version"           value="cli-6.3.0" />`
### Expected Behaviour
if debug mode turn ON from phonegap website and rebuild using https://build.phonegap.com again with  same code with new version then it shows like below type alert for navigator variable.
http://prntscr.com/cxetw3
### Actual Behaviour
if build using turn off debug mode like  http://prntscr.com/cxex2k then navigator always shows blank like
http://prntscr.com/cxetkd 
### Steps to Reproduce 
Turn Off for debug mode then rebuild app using phonegap build site. then add alert for navigator it will always shows as null.
#### Sample Code that illustrates the problem
use `<preference name="phonegap-version"           value="cli-6.3.0" />`
then rebuild from turn off debug mode and rebuild and also add alert.
#### Error messages
it shows null data for very first time app open for navigator variable

**Comment by surajpindoria** [comment]
Hi @mobileias,

This seems like it is an issue with PhoneGap Build and not the CLI. Can you repost this issue on the [Build forums](https://forums.adobe.com/community/phonegap/build). Also include some minimal source code to help replicate the issue.
