### ISSUE TITLE
Google Nexus 6 shows blank screen for apk created by phonegap site.

### ISSUE THREAD

**Issue by mobileias** [phonegap/phonegap-cli#657]
Hello

Here is our live google play store url
https://play.google.com/store/apps/details?id=com.instantautosite.oneshop
This build is created by phonegap build site (https://build.phonegap.com/)
We have used ionic html framework for this app.

We use phonegap 6.3.0 cli version

`<preference name="phonegap-version" value="cli-6.3.0" />`
`<plugin name="cordova-plugin-splashscreen" source="npm" version="4.0.0"/>`
`<plugin name="cordova-plugin-network-information" source="npm" version="1.3.0" />`
`<plugin name="cordova-plugin-statusbar" source="npm" version="2.2.0" />`
`<plugin name="cordova-plugin-device" source="npm" version="1.1.3" />`
`<plugin name="cordova-plugin-dialogs" source="npm" version="1.3.0" />`
`<plugin name="cordova-plugin-inappbrowser" source="npm" version="1.5.0" />`

also we have added some basic config preference for splashscreen related also and all is fine in other devices.

We checked almost all device and it working fine.
but last few days it shows blank screen on google nexus 6 device. (not open any page)
it has android 6 version.
it not shows any error log in console log
so can you please help me for this issue related. ?

**Comment by surajpindoria** [comment]
Hi @mobileias,

Sorry for the late reply. Unfortunately I don't have access to a Nexus 6 to test this myself. Do you see the same results if you build using the PhoneGap CLI?
