### ISSUE TITLE
PhoneGap Build - cli-6.3.0 gives wrong icon for iPhone 6 

### ISSUE THREAD

**Issue by amitdangwal** [phonegap/phonegap-cli#660]
The issue is already raised as part of ticket#636 but marked as closed however the issue is appearing on the iphone 6 till to the date. Please guide me what is wrong as app deployed on iphone(through adobe phonegap build) is showing incorrect app icon. Someone mentioned to add 2 more icons but issue still exist even after adding icons sized 58px and 87px square. It still showing cordova/phonegap icon instead of the one defined in the config.xml

 <icon src="www/icon.png" />
		<icon height="57" platform="ios" src="www/resources/icons/ios/icon.png" width="57" />
        <icon height="114" platform="ios" src="www/resources/icons/ios/icon@2x.png" width="114" />
        <icon height="40" platform="ios" src="www/resources/icons/ios/icon-40.png" width="40" />
        <icon height="80" platform="ios" src="www/resources/icons/ios/icon-40@2x.png" width="80" />
        <icon height="50" platform="ios" src="www/resources/icons/ios/icon-50.png" width="50" />
        <icon height="100" platform="ios" src="www/resources/icons/ios/icon-50@2x.png" width="100" />
        <icon height="60" platform="ios" src="www/resources/icons/ios/icon-60.png" width="60" />
        <icon height="120" platform="ios" src="www/resources/icons/ios/icon-60@2x.png" width="120" />
        <icon height="180" platform="ios" src="www/resources/icons/ios/icon-60@3x.png" width="180"/>
        <icon height="72" platform="ios" src="www/resources/icons/ios/icon-72.png" width="72" />
        <icon height="144" platform="ios" src="www/resources/icons/ios/icon-72@2x.png" width="144" />
        <icon height="76" platform="ios" src="www/resources/icons/ios/icon-76.png" width="76" />
        <icon height="152" platform="ios" src="www/resources/icons/ios/icon-76@2x.png" width="152" />
        <icon height="29" platform="ios" src="www/resources/icons/ios/icon-small.png" width="29" />
        <icon height="58" platform="ios" src="www/resources/icons/ios/icon-58.png" width="58" />
        <icon height="87" platform="ios" src="www/resources/icons/ios/icon-87.png" width="87" />

**Comment by surajpindoria** [comment]
Hi @amitdangwal,

I am unable to reproduce this issue myself using PhoneGap Build. Can you try updating your config.xml to use the following format. 

https://cordova.apache.org/docs/en/latest/config_ref/images.html#ios

Essentially just remove the `platform` attribute from each `icon` tag and put all the iOS icons in a `platform` tag.

**Comment by amitdangwal** [comment]
Hi @surajpindoria,

Issue is resolved and the concern was that the image resolution was not same as mentioned in config and that is why it was not picking the given image for me. I corrected the images and added with correct resolution. It was not the issue in CLI 5.2 but 6.3 seem to be more strict.

Warm Regards,
Amit Dangwal
