### ISSUE TITLE
Unexpected behaviour in iOS when run ios --device

### ISSUE THREAD

**Issue by faustoct** [phonegap/phonegap-cli#661]
### PhoneGap CLI, node & npm versions
phonegap 6.3.4
node 6.2.1
iphone 4
cordova-plugin-battery-status 1.1.2 "Battery"
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-contacts 2.0.1 "Contacts"
cordova-plugin-crosswalk-webview 2.0.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-device-motion 1.2.1 "Device Motion"
cordova-plugin-device-orientation 1.0.3 "Device Orientation"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-globalization 1.0.3 "Globalization"
cordova-plugin-http 1.2.0 "SSL Pinning"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-media 2.2.0 "Media"
cordova-plugin-media-capture 1.2.0 "Capture"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-vibration 2.1.1 "Vibration"
cordova-plugin-video-editor 1.1.2 "VideoEditor"
cordova-plugin-whitelist 1.2.2 "Whitelist"

### Expected Behaviour
normal navigation, access camera, without freezen.

### Actual Behaviour
screen freezes, can't access the camera, it works when I move out the app and come back, take to much to load, doesn't deal well with position: absolute (loading...) .

### Steps to Reproduce 
cordova run ios --device
It works fine in Android

**Comment by surajpindoria** [comment]
Hi @faustoct,

Not quite sure what the issue could be at this point. Could you try just removing the iOS platform and adding it, `cordova platform rm ios` and `cordova platform add ios`.

**Comment by faustoct** [comment]
Hi. I'm going to close. It is a Content-Security-Policy. I fixed it doing:
`    <meta http-equiv="Content-Security-Policy"   content="default-src * 'self' data: ws: gap: https://ssl.gstatic.com; media-src *;   style-src * 'self' 'unsafe-inline';   script-src * 'self' 'unsafe-inline' 'unsafe-eval' gap:"/>`
