### ISSUE TITLE
Debug Mode issue in phonegap cli - 6.3.0 for ios

### ISSUE THREAD

**Issue by GarthDB** [phonegap/phonegap-cli#665]
@mobileias commented on [Sat Oct 29 2016](https://github.com/phonegap/phonegap-docs/issues/230)

### PhoneGap CLI, node & npm versions

`<preference name="phonegap-version"           value="cli-6.3.0" />`
### Expected Behaviour

if debug mode turn ON from phonegap website and rebuild using https://build.phonegap.com again with  same code with new version then it shows like below type alert for navigator variable.
http://prntscr.com/cxetw3
### Actual Behaviour

if build using turn off debug mode like  http://prntscr.com/cxex2k then navigator always shows blank like
http://prntscr.com/cxetkd 
### Steps to Reproduce

Turn Off for debug mode then rebuild app using phonegap build site. then add alert for navigator it will always shows as null.
#### Sample Code that illustrates the problem

use `<preference name="phonegap-version"           value="cli-6.3.0" />`
then rebuild from turn off debug mode and rebuild and also add alert.
#### Error messages

it shows null data for very first time app open for navigator variable

---

@GarthDB commented on [Wed Nov 23 2016](https://github.com/phonegap/phonegap-docs/issues/230#issuecomment-262600646)

@mobileias is this a problem with the docs? Sounds like we should move this to the [PhoneGap CLI](https://github.com/phonegap/phonegap-cli). Would you like me to move it?

**Comment by filmaj** [comment]
Closing as no response from @mobileias. If this is still an issue, feel free to re-open and work together with us in trying to resolve the issue.
