### ISSUE TITLE
Unable to open asset URL: file:///android_asset/www/cordova_plugins.js

### ISSUE THREAD

**Issue by palomatamarkteody02** [phonegap/phonegap-cli#667]
Hi,
im using  cordova 6.4.1 and android 6.0.0,
android studio say there is  an error : Unable to open asset URL: file:///android_asset/www/cordova_plugins.js?
screenshot:
emulator:
![image](https://cloud.githubusercontent.com/assets/23630004/20618751/c3a4bb60-b32b-11e6-96d4-86c8cfee9d9f.png)
Asset folder:
![image](https://cloud.githubusercontent.com/assets/23630004/20618792/05289c6e-b32c-11e6-8838-41db4d668336.png)

Thanks in advance,

**Comment by surajpindoria** [comment]
What version of `cordova-plugin-admob` are you using? I just tried using the latest and I am able to open the project in Android Studio and I see that `cordova_plugins.js` is in the www directory.

**Comment by palomatamarkteody02** [comment]
I'm using cordova-plugin-simple, i already solved it by downgrading  android platform from 6.0.0 to 5.1.1.
Thanks for your quick response. :)

**Comment by surajpindoria** [comment]
Ok great! Going to close this issue out then.
