### ISSUE TITLE
Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by mobileias** [phonegap/phonegap-cli#669]
We are using phonegap cli version cli-6.3.0
and also using pushwoosh plugin version 6.3.2 

We are currently facing issue like 
http://prnt.sc/dibrwd

Since last 8th Dec 2016 till now.

As previous just one day we have already created new build and it working fine.
Just after one day we rebuild with same type code and app give above type error.
Any one have solution please ?

we are not able to upload our latest build even for testflight.

We create ipa using phonegap build website.

**Comment by surajpindoria** [comment]
From that message it seems that your app and associated distribution provisioning profile are not set up to use push notifications. You will need to go into Apples Developer Portal and update both to use push.
