### ISSUE TITLE
localtunnel! Urgent!

### ISSUE THREAD

**Issue by bryancresswell** [phonegap/phonegap-cli#670]
Is there a way to rename the subdomain when i run on localtunnel? I'm trying to let a few users try it out without having to type in the garbled stuff.

**Comment by surajpindoria** [comment]
Hi @bryancresswell,

Currently we do not support this functionality but it is definitely something that we can look into.

**Comment by filmaj** [comment]
If we are using localtunnel.me, I do not think there is an easy way to have that third party service expose domain name customization. We'd have to control this via our own server-side feature.

I am closing this for now. If someone disagrees with me, feel free to re-open, however I do not think this is something that PhoneGap can take on at the moment (cc @mwbrooks ).
