### ISSUE TITLE
CSP meta is transformed in phonegap serve

### ISSUE THREAD

**Issue by miqmago** [phonegap/phonegap-cli#674]
### PhoneGap CLI, node & npm versions
phonegap-cli: 6.0.1
node: 6.9.1
npm: 4.0.1

### Expected Behaviour
CSP respected in `phonegap serve`

### Actual Behaviour
CSP is automatically changed

### Steps to Reproduce 

1. Prepare an `index.html` with following directive:

```html
<meta http-equiv="Content-Security-Policy" content="default-src gap: file: tel: *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src 'self' 'unsafe-inline' *">
```

2. Start `phonegap serve` in cli:

```[phonegap] starting app server...
[phonegap] executing 'cordova prepare browser'...
[phonegap] listening on 192.168.1.130:3000
[phonegap] 
[phonegap] ctrl-c to stop the server
[phonegap] 
[phonegap] completed 'cordova prepare browser'
```

3. Check that `platforms/browser/www/index.html` has correct `<meta ...` tag 👍 

4. Download phonegap zip package from  `http://192.168.1.130:3000/__api__/appzip`

5. Extract the downloaded package and look for `<meta ...` tag in `www/index.html`. Oh surprise!! Where is `gap:` in meta tag ??

```html
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'">
```

`config.xml` file:

```xml
<content src="index.html" />
<access origin="*" />
<access origin="cdvfile://*" />
<access launch-external="yes" origin="tel:*" />

<!-- Allowed WebView navigations -->
<allow-navigation href="http://*"/>
<allow-navigation href="https://*"/>
<allow-navigation href="http://*/*"/>
<allow-navigation href="https://*/*"/>
<allow-navigation href="data:*"/>
<allow-navigation href="about:*"/>
<allow-navigation href="tel:*"/>
<allow-navigation href="gap:*" />
<!-- Allowed URLs to be opened from the app -->
<allow-intent href="http://*"/>
<allow-intent href="https://*"/>
<allow-intent href="http://*/*"/>
<allow-intent href="https://*/*"/>
<allow-intent href="geo:*"/>
<allow-intent href="cdvfile://*" />
```

Previously reported in http://stackoverflow.com/questions/41302230/phonegap-app-content-security-police

#### Error messages

```
Refused to load gap://ready because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy.
```

**Comment by surajpindoria** [comment]
Hi @miqmago,

This is actually not a bug with `phonegap serve` but the intended behavior. The updated CSP is required for the serve functionality to work on devices. We are not changing the CSP in your app, but only the version that is loaded to your device.

Going to close this, but feel free to comment back if you have further questions.

**Comment by miqmago** [comment]
@surajpindoria thanks. The problem is that in this situation, in iPad (I supose that in iOS in general), deviceready never get's launched:

```
Refused to load gap://ready because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy.
```

**Comment by miqmago** [comment]
Maybe `phonegap serve` could explicitely include ` gap: data:` and other useful schemas...

**Comment by surajpindoria** [comment]
Here is where we are creating our CSP that is injected and we are adding those already. There may be something else going on that is messing this up for you.

https://github.com/phonegap/connect-phonegap/blob/master/lib/util/csp-builder.js

**Comment by miqmago** [comment]
This is quite strange:

```
$ npm i phonegap -g
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/Users/miqmago/.nvm/versions/node/v6.9.1/bin/phonegap -> /Users/miqmago/.nvm/versions/node/v6.9.1/lib/node_modules/phonegap/bin/phonegap.js
/Users/miqmago/.nvm/versions/node/v6.9.1/lib
└─┬ phonegap@6.4.2 
...
$ which phonegap
/Users/miqmago/.nvm/versions/node/v6.9.1/bin/phonegap
$ phonegap -v
6.0.1
$ ~/.nvm/versions/node/v6.9.1/lib/node_modules/phonegap/bin/phonegap.js -v
6.4.2
```
