### ISSUE TITLE
Error when running 'phonegap share' in a new project

### ISSUE THREAD

**Issue by shazron** [phonegap/phonegap-cli#677]
### PhoneGap CLI, node & npm versions
```
$ phonegap --version
6.4.3
$ npm --version
2.15.11
$ node --version
v4.7.2
```

### Expected Behaviour

`phonegap share` runs without error, and/or shows a warning that the browser platform needs to be added first.

### Actual Behaviour

`phonegap share` runs with an error:
```
$ phonegap share

/Users/shaz/.nvm/versions/node/v4.7.2/lib/node_modules/phonegap/lib/phonegap/util/dropbox.js:186
            throw err;
            ^
directory: /Users/shaz/Desktop/test2/platforms/browser/www
```

### Steps to Reproduce 
```
phonegap create test
cd test
phonegap share
```

#### Workaround

Do a `phonegap platform add browser` first.

**Comment by imhotep** [comment]
Fixed
