### ISSUE TITLE
cli-6.5.0 - Breaks "keyboard accessory bar"? Location of updates?

### ISSUE THREAD

**Issue by c2-erogers** [phonegap/phonegap-cli#682]
NOTE: This update to PhoneGap `cli-6.5.0` was suggested via [PhoneGap Build](https://build.phonegap.com/) .. but I don't see that version here at all?  Where is the location of this version of updates?  It is on the list of [PhoneGap Versions](https://build.phonegap.com/current-support).

### PhoneGap CLI, node & npm versions
PhoneGap `cli-6.5.0`
NPM `2.15.8`
Node `4.4.7`

### Expected Behaviour
"HideKeyboardFormAccessoryBar(boolean)" defaults to false and works.

### Actual Behaviour
"HideKeyboardFormAccessoryBar(boolean)" preferences seems to have no impact within config.xml and cordova keyboard plugin.  The Accessory Bar is just always hidden even though it is defaulted to false.

### Steps to Reproduce 

- Build app with PhoneGap `cli-6.3.0` and see that "HideKeyboardFormAccessoryBar" is defaulted to false and the bar itself is visible in the app.
- Without modifying config.xml at all, upgrade to `cli-6.5.0`
- Rebuild app and observe that the bar itself is now hidden.  
- No config.xml settings or plugins bring it back.  
- Revert to `cli-6.3.0` and see that keyboard accessory bar is back (as expected), with or without "HideKeyboardFormAccessoryBar" preferences set in config.xml or plugins via JavaScript.

#### Sample Code that illustrates the problem
N/A

#### Error messages
N/A

**Comment by wildabeast** [comment]
Just to confirm, are you building locally or remotely on [PhoneGap Build](http://build.phonegap.com)?

You're right it doesn't make a lot of sense that PGB has released that version when the Phonegap CLI hasn't released it yet. However you can see the specific version breakdown [here](https://build.phonegap.com/current-support).

Maybe also share the exact xml you're using in your config.xml to set HideKeyboardFormAccessoryBar.

**Comment by wildabeast** [comment]
Assuming you're on PGB, might also be worth trying `cli-6.4.0` to verify when the issue was introduced.

**Comment by c2-erogers** [comment]
@wildabeast - This particular comment is based on building remotely on [PhoneGap Build](http://build.phonegap.com/).  I can build some out locally though to compare and follow up here once I get a chance.

The notice received is :
> This app isn't using the latest version of PhoneGap. We recommend upgrading to cli-6.5.0.

The config.xml file doesn't seem to actually have any affect; with a bare-bones config.xml (without the 'HideKeyboardFormAccessoryBar' preference set), _cli-6.3.0_ shows the accessory bar and _cli-6.5.0_ **does not**.  However, using cli-6.5.0 with the 'HideKeyboardFormAccessoryBar' preference set to 'false' does not help.


`
<plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
<preference name="HideKeyboardFormAccessoryBar" value="false" />
`

and

`cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);`

Do not re-enable this accessory bar in cli-6.5.0.  That said, it shouldn't be necessary at all as it should default to false from the documentation [https://cordova.apache.org/docs/en/latest/config_ref/index.html](https://cordova.apache.org/docs/en/latest/config_ref/index.html)

**Comment by c2-erogers** [comment]
@wildabeast - Following up on your second comment; _cli-6.4.0_ works as expected (like _cli-6.3.0_).

**Comment by wildabeast** [comment]
Thats interesting ... from the [PGB version breakdown](https://build.phonegap.com/current-support) the iOS versioning is:

- cli-6.4.0 uses cordova-ios 4.3.0
- cli-6.5.0 uses cordova-ios 4.3.1

Surprising that a minor patch would introduce that issue ([here's the diff between those versions for interest's sake](https://github.com/apache/cordova-ios/compare/a59101b...8fe24d4), nothing jumps out that would cause this).

@c2-erogers if you're set up to do so, it would be very helpful if you did local builds of both cordova-ios 4.3.0 and 4.3.1, and see if the issue manifests.

**Comment by wildabeast** [comment]
Actually looking at the docs again `HideKeyboardFormAccessoryBar` is actually a Blackberry-only preference... so that preference having no effect is expected.

Nonetheless the change in keyboard behaviour is still an issue.

Assuming that this also occurs when building locally, can you log an issue with the keyboard-plugin at https://issues.apache.org/jira/browse/CB/?

If it doesn't manifest when building locally, it is likely a PGB issue and we can move from there.

**Comment by c2-erogers** [comment]
Those cli/cordova-ios versions match up within PGB, too, after a successful build.

I will definitely try building locally with both versions ASAP--likely won't get a chance until the weekend, but it is on my list if we don't discover I'm an idiot before then.

Good catch on the `HideKeyboardFormAccessoryBar`, I had not noticed. =(

**Comment by shazron** [comment]
`HideKeyboardFormAccessoryBar` was removed in cordova-ios 3.2.0
Looks like you are using the Ionic Keyboard Plugin, and it does not use the HideKeyboardFormAccessoryBar preference either. I don't think its a platform problem, but a plugin problem (since they would be the ones that have the code to modify the accessory bar).

**Comment by c2-erogers** [comment]
@shazron - This problem exists without the use of any preferences or plugins.  These preferences/plugins were only implemented in hopes of fixing the initial issue.

**Comment by shazron** [comment]
I can guarantee that the latest version of cordova-ios does not have any code that touches the accessory bar, nor does it handle `HideKeyboardFormAccessoryBar` nor does `HideKeyboardFormAccessoryBar` occur anywhere -- so adding/not adding that pref should not make any difference.

**Comment by c2-erogers** [comment]
Right.  It does not make any difference.  My initial dump is misleading because I was trying to use `HideKeyboardFormAccessoryBar` to fix the issue at hand.

**Comment by shazron** [comment]
Getting back to the question: `Does cordova-cli 6.5.0 / cordova-ios 4.3.1 hide the keyboard accessory bar?`

The answer for me is `No` based on my test below. I just created a quick new project:
```
$ cordova --version
6.5.0
$ cordova create test
Creating a new cordova project.
$ cd test
$ cordova platform add ios
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.cordova.hellocordova
	Name: HelloCordova
iOS project created with cordova-ios@4.3.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for ios
```
Added a simple: `<input type="text" value="sometext" style="width:100px"/>` to `www/index.html` and touched it (iOS 10). The accessory bar is still there.

**Comment by wildabeast** [comment]
Ok thanks @shazron, might be PGB only, I'll try it out asap

**Comment by filmaj** [comment]
Unclear to me whether this is a PGB issue or a CLI issue. Any updates on this thread, @wildabeast / @c2-erogers ?

**Comment by c2-erogers** [comment]
@filmaj - I am unsure; I haven't had time to dig in and help test like I had hoped.  

But, as an update, I'm assuming it was either a PGB issue that was fixed or just something **I** was doing incorrectly.  I updated again in March and **it worked as expected** (As far as I recall, I didn't change anything that would have resolved the issue).

**Comment by filmaj** [comment]
Excellent! In that case I am closing the issue down - feel free to re-open if you see it crop up once more.
