### ISSUE TITLE
Update analytics to use metrics.phonegap.com

### ISSUE THREAD

**Issue by timkim** [phonegap/phonegap-cli#686]
Need to update the analytics to use new metrics.phonegap.com endpoint and use the GELF format.

**Comment by filmaj** [comment]
One thing to think about is if we want to change how to structure the events in GELF. GELF gives us complete freedom in using whatever JSON structure we wish. The challenge with Google Analytics is that all event data must fit into `category`, `action`, `label` and `value` fields - and only those fields - and we do that with a combination of [`bin/phonegap.js` code](https://github.com/phonegap/phonegap-cli/blob/master/bin/phonegap.js#L38-L43) as well as [a non-trivial `sanitize_args` module that fits the commands into those four fields](https://github.com/phonegap/phonegap-cli/blob/master/lib/cli/util/sanitize-args.js).

Currently, the top-level command (like `run`, `build`, `help`) is logged under `category`. All further parameters (like a platform directive like `ios`, or flags like `--debug`) are munged into one string and logged under `action`. `label` holds the exit code of the command. `value` _sometimes_ holds the "count" of parameters - but the [count is also sometimes munged into the `action`](https://github.com/phonegap/phonegap-cli/blob/master/lib/cli/util/sanitize-args.js#L103).

From an OCD and data-structuring perspective, I think it would be nice to have metrics.phonegap.com hold JSON documents that are more human-readable by making the structure of the documents represent the commands more naturally. This is not a proposal, but off the top of my head something like:

```
{
    "command":"run",
    "targetPlatform":"android", // if specified, or perhaps can be logged implicitly
    "flags":["--device", "--debug"]
}
```

On the flip side, this is more work to achieve, and the filtering and processing of data can be done at the reporting level on metrics.phonegap.com (via Kibana), as we have the full power of ElasticSearch at our disposal.

So, I don't know. I yield to the will of the mob!

cc @purplecabbage, @mwbrooks, @surajpindoria

**Comment by timkim** [comment]
I agree with the above about making the json more readable instead of just jamming the info in one of the properties. Perhaps we can move this discuss in the parent analytics thread to figure out what the structure should look like?

**Comment by filmaj** [comment]
I'm tracking my updates for this issue in my branch here: https://github.com/filmaj/phonegap-cli/tree/686-analytics-draft

Pull it down, `npm install`, and then you can get a sense of the event object by running `node analytics_test.js`:

```
➔ node analytics_test.js
Example event: { version: '1.1',
  host: 'cli',
  short_message: 'plugin',
  _params: [ 'add', 'cordova-plugin-camera' ],
  _flags: [ '--debug' ],
  _userID: 747796560480,
  _appVersion: '6.4.5+cordova.6.4.0',
  _nodeVersion: 'v6.9.4',
  _platform: 'macOS Sierra',
  _env: 1 }
```

I've started to update the logic in that branch, as well:
 - it uses the same GA client ID for userId (based on the `insight` module's implementation).
 - puts the top-level command invoked under `short_message`. Gonna point that out in the top-level discuss thread in case we want to tweak that.
 - flags are under `_flags`
 - parameters are under `_params`
 - leverages `os-name` module for `_platform`, to align with the same OS names we are currently storing in GA (based on the `insight` module's implementation).
 -
