### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by mlantz** [phonegap/phonegap-cli#69]
If you guys could add a JSON output to the CLI I could write a PySide GUI for the CLI.

**Comment by hiddentao** [comment]
This would be quite interesting. In fact, perhaps JSON output can be added to the cordova cli lib itself so that Phonegap can just piggy-back on that one.

**Comment by mwbrooks** [comment]
@hiddentao I agree, if this was implemented, then we'd want to see it happen at the Apache Cordova CLI level and not the PhoneGap CLI level.

**Comment by mlantz** [comment]
That would by far make the most sense, I haven't looked at Cordova in a long while, maybe its time to get reacquainted

**Comment by filmaj** [comment]
I am confused as to what this issue is about. Can someone provide more information?

**Comment by mlantz** [comment]
It was an idea I had at one point. I think we can close this and let it be. I haven't kept up with the project I'm lost on what tools are out there now that work with it
