### ISSUE TITLE
When commands exit with non-zero exit codes, ensure to tack on stack trace information when reporting via analytics

### ISSUE THREAD

**Issue by filmaj** [phonegap/phonegap-cli#698]
@hermwong does the desktop app do that already?

**Comment by hermwong** [comment]
The Desktop sends the stack trace as `error_stack` whenever it catches any exceptions in the `windows.onerror` event.

See attached screen shot.

<img width="1009" alt="screen shot 2017-04-05 at 2 29 07 pm" src="https://cloud.githubusercontent.com/assets/107754/24727820/472998d8-1a0c-11e7-8058-cf7edee97c51.png">

**Comment by filmaj** [comment]
Thanks @hermwong, I'll add that `error_stack` parameter to phonegap-metrics README.

**Comment by filmaj** [comment]
Fixed in 80298a5.
