### ISSUE TITLE
Error: android: Command failed with exit code 2

### ISSUE THREAD

**Issue by TomAshley303** [phonegap/phonegap-cli#707]
### PhoneGap CLI, node & npm versions
phonegap 6.4.8
node v7.9.0
npm 4.2.0

### Expected Behaviour
Emulator to run Webstorm/Phonegap demo app.

### Actual Behaviour
```
[phonegap] executing 'cordova run android --verbose ' ...
Error: Error
    at Object.cdProjectRoot (/usr/lib/node_modules/phonegap/node_modules/cordova-lib/src/cordova/util.js:151:15)
    at /usr/lib/node_modules/phonegap/node_modules/cordova-lib/src/cordova/run.js:30:40
    at _fulfilled (/usr/lib/node_modules/phonegap/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/phonegap/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/phonegap/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/phonegap/node_modules/q/q.js:810:14
    at flush (/usr/lib/node_modules/phonegap/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)



user@host:/usr/lib/jvm/java-8-openjdk-amd64$ phonegap --version
6.4.8
user@host:/usr/lib/jvm/java-8-openjdk-amd64$ nodejs --version
v7.9.0
user@host:/usr/lib/jvm/java-8-openjdk-amd64$ npm --version
4.2.0
user@host:/usr/lib/jvm/java-8-openjdk-amd64$ npm --version
4.2.0
user@host:/usr/lib/jvm/java-8-openjdk-amd64$ phonegap run android --verbose
[phonegap] executing 'cordova run android --verbose ' ...
Error: Error
    at Object.cdProjectRoot (/usr/lib/node_modules/phonegap/node_modules/cordova-lib/src/cordova/util.js:151:15)
    at /usr/lib/node_modules/phonegap/node_modules/cordova-lib/src/cordova/run.js:30:40
    at _fulfilled (/usr/lib/node_modules/phonegap/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/phonegap/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/phonegap/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/phonegap/node_modules/q/q.js:810:14
    at flush (/usr/lib/node_modules/phonegap/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
```
### Steps to Reproduce 
I started out with this error: https://github.com/phonegap/phonegap-cli/issues/685 and fixed it by extracting the templates folder from the standalone Android tools download. Now we have this problem.
Install Android Studio.
Start new Webstorm project...
$ phonegap run android --verbose
All environment variables are set.

#### Sample Code that illustrates the problem
config.xml: [https://hastebin.com/equqemabop.xml](https://hastebin.com/equqemabop.xml)
index.html: [https://hastebin.com/uvemufulof.xml](https://hastebin.com/uvemufulof.xml)
Lots of other files but all default Phonegap project in Webstorm.
#### Error messages
```
Error: Error
    at Object.cdProjectRoot (/usr/lib/node_modules/phonegap/node_modules/cordova-lib/src/cordova/util.js:151:15)
    at /usr/lib/node_modules/phonegap/node_modules/cordova-lib/src/cordova/run.js:30:40
    at _fulfilled (/usr/lib/node_modules/phonegap/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/phonegap/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/phonegap/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/phonegap/node_modules/q/q.js:810:14
    at flush (/usr/lib/node_modules/phonegap/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
```

**Comment by TomAshley303** [comment]
I just tried manually installing the SDK standalone. It's straight up broke.

**Comment by filmaj** [comment]
Are you running the `phonegap run android` command from a generated PhoneGap project? i.e. something like:

```
$ phonegap create myapp
$ cd myapp
$ phonegap platform add android
$ phonegap run android
```

From your paste above, it looks like you are trying to execute the `run` command from your JDK directory?

**Comment by TomAshley303** [comment]
Running those exact commands I get exit with error code so I run it with verbosity set and I get:

> 
> [phonegap] executing 'cordova run android --verbose ' ...
> No scripts found for hook "before_run".
> 
> 
> No scripts found for hook "before_prepare".
> 
> 
> Checking config.xml for saved platforms that haven't been added to the project
> 
> 
> Checking for any plugins added to the project that have not been installed in android platform
> 
> 
> No differences found between plugins added to project and installed in android platform. Continuing...
> 
> 
> Generating platform-specific config.xml from defaults for android at /home/user/Code/myapp/platforms/android/res/xml/config.xml
> 
> 
> Merging project's config.xml into platform-specific android config.xml
> 
> 
> Merging and updating files from [www, platforms/android/platform_www] to platforms/android/assets/www
> 
> 
> Wrote out android application name "helloworld" to /home/user/Code/myapp/platforms/android/res/values/strings.xml
> 
> 
> android-versionCode not found in config.xml. Generating a code based on version in config.xml (1.0.0): 10000
> 
> 
> Wrote out Android package name "com.phonegap.helloworld" to /home/user/Code/myapp/platforms/android/src/com/phonegap/helloworld/MainActivity.java
> 
> 
> Updating icons at res
> 
> 
> Updating splash screens at res
> 
> 
> Prepared android project successfully
> 
> 
> No scripts found for hook "after_prepare".
> 
> 
> Checking config.xml for saved plugins that haven't been added to the project
> 
> 
> ANDROID_HOME=/home/user/AndroidSdk
> 
> JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
> 
> Subproject Path: CordovaLib
> 
> Running command: /home/user/Code/myapp/platforms/android/gradlew cdvBuildDebug -b /home/user/Code/myapp/platforms/android/build.gradle -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2048m -Pandroid.useDeprecatedNdk=true
> 
> 
> Incremental java compilation is an incubating feature.
> 
> 
> :preBuild
>  UP-TO-DATE
> 
> :preDebugBuild
>  UP-TO-DATE
> 
> 
> :checkDebugManifest
> 
> :CordovaLib:preBuild
>  UP-TO-DATE
> :CordovaLib:preDebugBuild UP-TO-DATE
> :CordovaLib:checkDebugManifest
> 
> :CordovaLib:prepareDebugDependencies
> :CordovaLib:compileDebugAidl
>  
> UP-TO-DATE
> 
> :CordovaLib:compileDebugNdk
>  UP-TO-DATE
> 
> :CordovaLib:compileLint
>  UP-TO-DATE
> :CordovaLib:copyDebugLint UP-TO-DATE
> 
> :CordovaLib:mergeDebugShaders UP-TO-DATE
> 
> :CordovaLib:compileDebugShaders
>  UP-TO-DATE
> :CordovaLib:generateDebugAssets UP-TO-DATE
> :CordovaLib:mergeDebugAssets
>  
> UP-TO-DATE
> 
> :CordovaLib:mergeDebugProguardFiles
>  UP-TO-DATE
> 
> :CordovaLib:packageDebugRenderscript
>  
> UP-TO-DATE
> 
> :CordovaLib:compileDebugRenderscript
>  
> UP-TO-DATE
> :CordovaLib:generateDebugResValues UP-TO-DATE
> 
> :CordovaLib:generateDebugResources UP-TO-DATE
> :CordovaLib:packageDebugResources
>  
> UP-TO-DATE
> 
> :CordovaLib:processDebugManifest
>  
> UP-TO-DATE
> 
> :CordovaLib:generateDebugBuildConfig
>  
> UP-TO-DATE
> 
> :CordovaLib:processDebugResources
>  
> UP-TO-DATE
> 
> :CordovaLib:generateDebugSources UP-TO-DATE
> :CordovaLib:incrementalDebugJavaCompilationSafeguard
>  
> UP-TO-DATE
> 
> :CordovaLib:compileDebugJavaWithJavac
>  
> UP-TO-DATE
> :CordovaLib:processDebugJavaRes
>  
> UP-TO-DATE
> 
> :CordovaLib:transformResourcesWithMergeJavaResForDebug
>  
> UP-TO-DATE
> 
> :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
>  
> UP-TO-DATE
> 
> :CordovaLib:mergeDebugJniLibFolders
>  
> UP-TO-DATE
> 
> :CordovaLib:transformNative_libsWithMergeJniLibsForDebug
>  
> UP-TO-DATE
> 
> :CordovaLib:transformNative_libsWithSyncJniLibsForDebug
>  
> UP-TO-DATE
> 
> :CordovaLib:bundleDebug
>  
> UP-TO-DATE
> 
> :prepareAndroidCordovaLibUnspecifiedDebugLibrary
>  
> UP-TO-DATE
> 
> :prepareDebugDependencies
> 
> 
> :compileDebugAidl
>  
> UP-TO-DATE
> 
> :compileDebugRenderscript
>  
> UP-TO-DATE
> 
> :generateDebugBuildConfig
>  
> UP-TO-DATE
> 
> :generateDebugResValues
>  
> UP-TO-DATE
> 
> :generateDebugResources
>  UP-TO-DATE
> 
> 
> :mergeDebugResources
>  
> UP-TO-DATE
> :processDebugManifest
>  UP-TO-DATE
> :processDebugResources
>  
> UP-TO-DATE
> 
> :generateDebugSources UP-TO-DATE
> :incrementalDebugJavaCompilationSafeguard UP-TO-DATE
> :compileDebugJavaWithJavac UP-TO-DATE
> :compileDebugNdk UP-TO-DATE
> :compileDebugSources UP-TO-DATE
> :mergeDebugShaders 
> UP-TO-DATE
> :compileDebugShaders UP-TO-DATE
> :generateDebugAssets UP-TO-DATE
> :mergeDebugAssets
>  UP-TO-DATE
> 
> 
> :transformClassesWithDexForDebug
>  
> UP-TO-DATE
> 
> :mergeDebugJniLibFolders
>  
> UP-TO-DATE
> :transformNative_libsWithMergeJniLibsForDebug
>  
> UP-TO-DATE
> :processDebugJavaRes
>  UP-TO-DATE
> :transformResourcesWithMergeJavaResForDebug
>  UP-TO-DATE
> :validateSigningDebug
> 
> :packageDebug
>  UP-TO-DATE
> 
> :assembleDebug UP-TO-DATE
> 
> :cdvBuildDebug
>  
> UP-TO-DATE
> 
> 
> 
> BUILD SUCCESSFUL
> 
> 
> 
> 
> Total time: 0.598 secs
> 
> Command finished with error code 0: /home/user/Code/myapp/platforms/android/gradlew cdvBuildDebug,-b,/home/user/Code/myapp/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Dorg.gradle.jvmargs=-Xmx2048m,-Pandroid.useDeprecatedNdk=true
> 
> 
> Built the following apk(s): 
>         /home/user/Code/myapp/platforms/android/build/outputs/apk/android-debug.apk
> 
> 
> No scripts found for hook "before_deploy".
> 
> 
> ANDROID_HOME=/home/user/AndroidSdk
> 
> JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
> 
> Running command: adb devices
> 
> 
> Command finished with error code 0: adb devices
> 
> 
> No target specified and no devices found, deploying to emulator
> 
> 
> Running command: adb devices
> 
> 
> Command finished with error code 0: adb devices
> 
> 
> Running command: android list avds
> 
> 
> Command finished with error code 2: android list,avds
> 
> 
> Error: android: Command failed with exit code 2
>     at ChildProcess.whenDone (/home/user/Code/myapp/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:194:7)
>     at maybeClose (internal/child_process.js:899:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

So I try: **phonegap platform rm android**
then:
**phonegap platform add android@6.2.1**
and I get:

> Error: cordovaProject.projectConfig.getFileResources is not a function

Run the phonegap emulate android again and I get:

> Error: TypeError: cordovaProject.projectConfig.getFileResources is not a function
>     at updateFileResources (/home/user/Code/myapp/platforms/android/cordova/lib/prepare.js:408:46)
>     at /home/user/Code/myapp/platforms/android/cordova/lib/prepare.js:51:9
>     at _fulfilled (/home/user/Code/myapp/platforms/android/cordova/node_modules/q/q.js:854:54)
>     at self.promiseDispatch.done (/home/user/Code/myapp/platforms/android/cordova/node_modules/q/q.js:883:30)
>     at Promise.promise.promiseDispatch (/home/user/Code/myapp/platforms/android/cordova/node_modules/q/q.js:816:13)
>     at /home/user/Code/myapp/platforms/android/cordova/node_modules/q/q.js:624:44
>     at runSingle (/home/user/Code/myapp/platforms/android/cordova/node_modules/q/q.js:137:13)
>     at flush (/home/user/Code/myapp/platforms/android/cordova/node_modules/q/q.js:125:13)
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by surajpindoria** [comment]
Hi @TomAshley303,

This is another error we have uncovered in the last few days, the version of cordova that we ship with phonegap is incompatible with the latest cordova-android. I will release a new version of phonegap with the latest cordova today.

**Comment by filmaj** [comment]
Yes, as per @surajpindoria, your second error is related to an incompatibility between currently-released phonegap-cli and cordova-android@6.2.1. We will need to release an update to phonegap-cli to fix that.

Your previous error is related to, I think, you using the latest Android SDK Tools (version 26), which makes the `android` command obsolete. You can verify this by running `android list avds` from your command-line. You might be able to get around this by manually running the Android emulator in a separate process, and ensuring it shows up when you run `adb devices`. Once you have the emulator running and `adb devices` recognizes it, you can try again w/ `phonegap run` - at that point the tool should recognize that you have a running emulator and go ahead and deploy directly to it.

**Comment by surajpindoria** [comment]
I have also just updated the phonegap-cli to use the latest version of cordova. So you should no longer see the second error message.

**Comment by filmaj** [comment]
@TomAshley303 closing this issue as we believe the latest release should fix the issue for you. If that is not the case, please feel free to re-open.

**Comment by TomAshley303** [comment]
```
Running command: android list avds


Command finished with error code 2: android list,avds


Error: android: Command failed with exit code 2
    at ChildProcess.whenDone (/home/user/Code/PhonegapTest/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)



:~/Code/PhonegapTest$ phonegap -v
6.5.0
:~/Code/PhonegapTest$ cordova -v
6.5.0
```

again with this

**Comment by filmaj** [comment]
@TomAshley303 what is the output of running `android list avds` ?

**Comment by TomAshley303** [comment]
```
android list avd
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Running /home/user/Android/Sdk/tools/bin/avdmanager list avd

Available Android Virtual Devices:
    Name: Nexus_5X_API_25_x86
  Device: Nexus 5X (Google)
    Path: /home/user/.android/avd/Nexus_5X_API_25_x86.avd
  Target: Google APIs (Google Inc.)
          Based on: Android 7.1.1 (Nougat) Tag/ABI: google_apis/x86
    Skin: nexus_5x
  Sdcard: 800M
Snapshot: no
```

**Comment by filmaj** [comment]
So as [I mentioned in my comment from 6 days ago](https://github.com/phonegap/phonegap-cli/issues/707#issuecomment-294970147), you are running the latest Android SDK which broke all the cordova-android things. You need to make sure you are a) using the latest phonegap-cli and b) explicitly using the cordova-android 6.2.1 version when adding the android platform. I.e.:

```
$ phonegap create someproject
$ cd someproject
$ phonegap platform add android@6.2.1
```

There is no other way to use phonegap and/or cordova with the latest Android SDK tools release that Google did last week. So either upgrade your phonegap/cordova bits, or downgrade your Android SDK.

You _might_ be able to get around this issue per the instructions in my previous comment:

> You might be able to get around this by manually running the Android emulator in a separate process, and ensuring it shows up when you run `adb devices`. Once you have the emulator running and adb devices recognizes it, you can try again w/ `phonegap run` - at that point the tool should recognize that you have a running emulator and go ahead and deploy directly to it.

**Comment by TomAshley303** [comment]
I got it to run by running the emulator first from Android Studio. Not ideal.

**Comment by filmaj** [comment]
As I've mentioned twice now, if you upgrade your cordova-android version, it should work.

Code that was written in the past (whatever version of cordova-android you are using) cannot possibly be compatible with SDKs that were unreleased at that time (Android SDK Tools v26 or newer).

**Comment by TomAshley303** [comment]
phonegap platform add android@6.2.1? It doesn't help.

**Comment by filmaj** [comment]
Ah damn. Sorry @TomAshley303, you were right, I was wrong. My apologies.

I mistook two recent similar patches in cordova-android that landed that both had to do with fixing compatibility with Android SDK updates ([one commit back in March to fix SDK Tools v25.3](https://github.com/apache/cordova-android/commit/4a354bba868e181e66ccebcfb446978e700b5891), [another commit from this month to fix SDK Tools v26+](https://github.com/apache/cordova-android/commit/765c4ee9f691445d0b437c5ff838c3ecb57e0e85)). The first commit made it into 6.2.1, the second commit did not.

For full compatibility, the Apache Cordova team needs to release a new version of cordova-android, which is currently in process.

One workaround, while we wait for a new cordova-android release, is to add the latest cordova-android code to your project (and not relying on tagged/released versions that are on npm). One way to do this is to clone the cordova-android source code and point `phonegap platform add` to the source:

```
$ git clone https://github.com/apache/cordova-android.git
$ cd cordova-android
$ npm install
$ cd ..
$ phonegap create myproject
$ cd myproject
$ phonegap platform add ../cordova-android
```

Then you would be including the latest cordova-android code in your phonegap project. I've verified this works with the latest SDK Tools (v26).

Once again, sorry for blaming you earlier - I should have spent more time verifying the issue.

**Comment by TomAshley303** [comment]
NP, I might do that.  I was actually just able to run the emulator from studio first and then phonegap run. So at least now I can emulate my projects. I'll just stick with that for now and keep updating until normal usage is fixed.

Thanks.

**Comment by trbsi** [comment]
@TomAshley303 that actually worked for me :D
