### ISSUE TITLE
phonegap create & NPM5 problem

### ISSUE THREAD

**Issue by ais-one** [phonegap/phonegap-cli#722]
### PhoneGap CLI, node & npm versions
Node v8.0.0
Node v5.0.0
Phonegap 6.4.8

### Expected Behaviour
Create a project

### Actual Behaviour
Cannot create a project

### Steps to Reproduce 
phonegap create test

#### Sample Code that illustrates the problem
N.A.

#### Error messages
Error: Unhandled "error" event. (  Error from Cordova Fetch: Error: cmd: Command failed with exit code 1 Error output:
npm ERR! Path must be a string. Received undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxxxxxxxxxxxx

**Comment by surajpindoria** [comment]
Hi @ais-one,

I have just tried this using node@8.0.0 and phonegap versions 6.4.8 and 6.5.0 and am unable to reproduce this error. Not sure yet what your issue is, are you using a proxy or anything that may affect the network calls made from cordova-fetch?

**Comment by ais-one** [comment]
you may b right, let me test on open network and revert

**Comment by ais-one** [comment]
I tested on NPM5, Node8, failed

reverted machine back to Node7.10.0 Npm4.2.0 it worked ok (same network conditions)

I attach the error log

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   'phonegap-template-hello-world' ]
> 2 info using npm@5.0.0
> 3 info using node@v8.0.0
> 4 silly install loadCurrentTree
> 5 silly install readLocalPackageData
> 6 silly pacote directory manifest for undefined@file:phonegap-template-hello-world fetched in 15ms
> 7 verbose stack TypeError: Path must be a string. Received undefined
> 7 verbose stack     at assertPath (path.js:28:11)
> 7 verbose stack     at Object.relative (path.js:560:5)
> 7 verbose stack     at computeVersionSpec (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:282:27)
> 7 verbose stack     at Installer.normalizeCurrentTree (C:\Program Files\nodejs\node_modules\npm\lib\install.js:370:69)
> 7 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
> 7 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
> 7 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
> 7 verbose stack     at iferr (C:\Program Files\nodejs\node_modules\npm\lib\install.js:328:5)
> 7 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
> 7 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
> 7 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\call-limit\call-limit.js:22:12
> 7 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:95:7)
> 7 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
> 8 verbose cwd C:\Users\aaron.gong\.cordova\node_modules
> 9 verbose Windows_NT 6.1.7601
> 10 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "phonegap-template-hello-world"
> 11 verbose node v8.0.0
> 12 verbose npm  v5.0.0
> 13 error Path must be a string. Received undefined
> 14 verbose exit [ 1, true ]
>

**Comment by surajpindoria** [comment]
Hrmm, this is very weird indeed. I also didn't realize you were on Windows so I retested today and still was not able to reproduce. Will continue looking into this.

**Comment by ais-one** [comment]
I will also try things out soon using node 8 npm 5 again, see what happens. How I upgrade or downgrade was simply to run the MSI.

Let me know if there is something you need to try.

I am on 64 bit windows 7 Professional SP1, 16GB RAM, Xeon

**Comment by ais-one** [comment]
I would like to close this, I am not getting the issue anymore...
