### ISSUE TITLE
Apple watch icon is using phonegap default

### ISSUE THREAD

**Issue by NicolaiFriis** [phonegap/phonegap-cli#723]
### PhoneGap CLI, node & npm versions
PhoneGap (iOS / Android / Windows)
cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)

onesignal-cordova-plugin   	npm	2.0.11

### Expected Behaviour
It should show the app icon on the notification. Its working on a iPhone 6Plus and on a iPad.

### Actual Behaviour
Its showing the default phonegap icon.

### Steps to Reproduce 
Setup a phonegap with onesignal-cordova-plugin plugin - when sending notifications from onesignal it shows my custom icon on a iPhone6Plus and a iPad. On my Apple Watch its showing the phonegap icon.

#### Sample Code that illustrates the problem
None

#### Error messages
None

**Comment by surajpindoria** [comment]
Hi @NicolaiFriis,

You most likely have not included the right icon sizes for the Apple Watch, which would explain why it is using the default PhoneGap icon. I have posted a link below that talks about Apple Watch icon sizes.

https://stackoverflow.com/questions/29583783/correct-apple-watch-icon-sizes-and-resolution

**Comment by NicolaiFriis** [comment]
Hi @surajpindoria 

As you can see below i already have the images includes in the res folder.
<img width="872" alt="skaermbillede 2017-06-06 kl 10 36 10" src="https://cloud.githubusercontent.com/assets/25979285/26820699/049ab4c0-4aa4-11e7-9b63-77ec2fbfd049.png">

And in my config.xml it looks like this: 

        
        <icon src="res/icons/ios/icon-40@2x.png" platform="ios" width="80" height="80" /> 
        
        <icon src="res/icons/ios/icon-44@2x.png" platform="ios" width="88" height="88" /> 
        
        <icon src="res/icons/ios/icon-86@2x.png" platform="ios" width="172" height="172" /> 
        
        <icon src="res/icons/ios/icon-98@2x.png" platform="ios" width="196" height="196" /> 
        
        <icon src="res/icons/ios/icon-24@2x.png" platform="ios" width="48" height="48" /> 
        
        <icon src="res/icons/ios/icon-27.5@2x.png" platform="ios" width="55" height="55" /> 
        
        <icon src="res/icons/ios/icon-29@2x.png" platform="ios" width="58" height="58" /> 
        
        <icon src="res/icons/ios/icon-29@3x.png" platform="ios" width="87" height="87" /> 

One thing i noticed, firstly when i had problems with the icon being the phonegap one i could make the .ipa to a .zip and open it up and see that inside there was a phonegap icon. This is not happening with the apple watch. All images in the ipa is my logo OR splash screen. So im not sure where it gets the phonegap icon.

**Comment by surajpindoria** [comment]
That is very strange @NicolaiFriis.

I also just tested this using the PhoneGap Developer App and our own push service, and the icon on my Apple Watch is being displayed correctly. Even weirder is that we do not include any of the Apple Watch icons in the Developer App. I will need to continue looking into your issue.

**Comment by surajpindoria** [comment]
Hey @NicolaiFriis,

I have chatted with a few people and I think the issue might be that in cordova we don't do anything with Apple Watch icons. Here is a [list](https://github.com/apache/cordova-ios/blob/a9532aed061ede7f322ab4d6843dcb8e235fce9e/bin/templates/scripts/cordova/lib/prepare.js#L313-L328) of the icons that do currently get handled properly. Since we do not provide official support for Apple Watch this would explain what is happening.

If this is something that you need for your app then we can file a feature request to add support for it.

**Comment by NicolaiFriis** [comment]
@surajpindoria that would be awesome if we could submit a feature request. I would like to show our app icon on the apple watch notifications. I do not think that many of our users have a Apple Watch but i still want to make sure it looks good if they do have it. Thanks 👍

**Comment by surajpindoria** [comment]
No problem, I will file this in the cordova issue tracker.

**Comment by NicolaiFriis** [comment]
@surajpindoria do you have a link for the feature request, so i can follow up on any updates? :)

**Comment by surajpindoria** [comment]
https://issues.apache.org/jira/browse/CB-12896
