### ISSUE TITLE
Blocks fs write for newly produced file

### ISSUE THREAD

**Issue by whitecolor** [phonegap/phonegap-cli#727]
Autoreload watching blocks FS write for new file that appears.

While build I ve got the error when new bundle file (not changed version but new) is produced:
![image](https://user-images.githubusercontent.com/736697/27379004-143b0d6c-5693-11e7-99d3-48cab3cd1fec.png)

And ouput of `phonegap serve`:
![image](https://user-images.githubusercontent.com/736697/27378965-fe136ad4-5692-11e7-9e4c-0d35eacd03d3.png)

It probably catches file as soon it only is started to be written on FS. So it probably could be fixed by som settings for polling or something.

In general pg serve watching and autoreload works strange and unreliable way comparing to other things like bundles (webpack etc), that is why I didn't want to use it.

This probably should be a separate issue.

Phone gap is working in docker container and files are on attached volume.

**Comment by whitecolor** [comment]
UPD: but maybe this is bug due to docker/host FS interaction, will update the issue status.

**Comment by purplecabbage** [comment]
running in a container is out of scope for us.  If you have done some work towards this, we would love to see a pull request.
