### ISSUE TITLE
Move cordova telemetry do not track

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-cli#728]
Currently we add the cordova `--no-telemetry` flag in `lib/cli/cordova.js` but when running `phonegap create ...` commands we do not enter that file, instead going straight to `lib/phonegap/cordova.js`. This will result in double analytics tracking, cordova and phonegap, but also some unintended side effects when running the CLI from the desktop app.

**Comment by purplecabbage** [comment]
fixed by @surajpindoria
