### ISSUE TITLE
Add support for environment-specific platforms

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-cli#73]
Sometimes, the environments support different platforms. For example, BlackBerry 10 is supported locally and BlackBerry 6 is supported remotely. Symbian is only remote. WP8 is only local.

We should display meaningful errors when the incorrect platform is targeted.

We should also throw meaningful errors when an invalid platform is targeted.

**Comment by filmaj** [comment]
@mwbrooks moar context please! What is the problem this issue is trying to describe?

**Comment by filmaj** [comment]
Ping ping Mr @surajpindoria

**Comment by surajpindoria** [comment]
Not really sure what remote platforms are, but AFAIK all the platforms we currently support need to be built locally. I'd it's safe to close this.
