### ISSUE TITLE
phonegap serve throws unhandled exception

### ISSUE THREAD

**Issue by JhonnyJason** [phonegap/phonegap-cli#732]
There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
Error: watch /home/lenny/temp/devapp/www/ ENOSPC
    at _errnoException (util.js:1041:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at Gaze._watchDir (/usr/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:304:30)
    at /usr/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:377:10
    at iterate (/usr/lib/node_modules/phonegap/node_modules/gaze/lib/helper.js:69:5)
    at Object.forEachSeries (/usr/lib/node_modules/phonegap/node_modules/gaze/lib/helper.js:83:3)
    at Gaze._initWatched (/usr/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:373:10)
    at Gaze.add (/usr/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:192:8)
    at new Gaze (/usr/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:74:10)

**Comment by surajpindoria** [comment]
Hey @JhonnyJason,

After a quick google search the error you seeing, ENOSPC, seems to be related to insufficient space on the drive. From the link below the suggestions include clearing up some files from your temp folder or setting a new temp folder for npm to use instead.

https://stackoverflow.com/questions/22475849/node-js-error-enospc

**Comment by JhonnyJason** [comment]
Hmm this is weird - I have ~7GB left on the drive basicly should be enough

For the error it appears to happen randomly, just managed to have "$ phonegap serve" running :-) as I did before this error - without any significant changes to the system...

Stepping to the next Problem the connection to the Phonegap developer App does not work somehow, but is a different Problem which I will search after some bit of sleep :-) maybe it's only halluziations because of brainfog.^^

THanx for the fast reply!

**Comment by JhonnyJason** [comment]
Ah now I get it!

It refers to RAM-FS, my /tmp partition - depending on other Applications simutanously running it becomes filled and that produces that error :-)

**Comment by JhonnyJason** [comment]
Ok sorry that was a premature assumption.

Just created a the hello-world sample app
$ phonegap create sample-app
$ cd sample-app
$ phonegap serve

again...

[phonegap] starting app server...
There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
Error: watch /home/lenny/temp/sample-app/www/css/ ENOSPC
    at _errnoException (util.js:1041:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at Gaze._watchDir (/usr/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:304:30)
    at /usr/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:377:10
    at iterate (/usr/lib/node_modules/phonegap/node_modules/gaze/lib/helper.js:69:5)
    at Object.forEachSeries (/usr/lib/node_modules/phonegap/node_modules/gaze/lib/helper.js:83:3)
    at Gaze._initWatched (/usr/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:373:10)

While currently I have 7Gb free drive space
and 3.8Gb free space in the tmpfs /tmp partition 

Also other tmpfs also have alot free space so this appears to be an unjustified error, which randomly appears. 
Unfortunately I have no clue what could be other relevant information about this issue, or if it even is a Phonegap-CLI bug - maybe it is nodejs? 

I will update here when I have more useful observative information, what correlates with the situation where it just works to when it does not.

**Comment by filmaj** [comment]
@JhonnyJason so does your `/home/lenny/temp/sample-app` directory sit on the `tmpfs` `/tmp` partition?

The `ENOSPC` errors seems to be coming from the gaze module, which I believe the cli uses to watch for filesystem changes, enabling the auto-refresh/reload feature of `phonegap serve`. One possible workaround could be to try with the `--no-autoreload` flag to see if that can avoid the error.

This might be tough to reproduce without understanding your system better, like the partition/directory setup, the OS you are running, node version, etc.

**Comment by JhonnyJason** [comment]
ok I'm using Arch Linux kernel - 4.12.8-2-ARCH
node version: v8.4.0
phonegap version: 7.0.0
npm version: 5.3.0

$ df -h  
prints (headline translated^^):
fs              size        used   avail.  perc.  mountpoint
dev            3,9G       0       3,9G    0%      /dev
run             3,9G      1,1M  3,9G    1%      /run
/dev/sdb3   58G       49G    6,7G   88%     /
tmpfs          3,9G      53M   3,8G    2%      /dev/shm
tmpfs          3,9G      0        3,9G    0%      /sys/fs/cgroup
tmpfs          3,9G      3,4M  3,9G    1%      /tmp
/dev/sdb2    194M    59M    122M  33%     /boot
tmpfs           788M    4,0K   787M  1%       /run/user/1000

The home folders and all folders within those are inside the / partition using  /dev/sdb3 which has 6.7Gb available space. This also includes the ~/temp/sample-app and the ~/temp/devapp folder.

**Comment by JhonnyJason** [comment]
and yhea it is probably the gaze module itself
The workraround to not gaze at filechanges works :-) thanx!

another question btw. isn't phonegap developer App compatible to Android 7.0.0, or is it but not with my device? 
When I compile it myself I can do -  $ phonegap run android - and it will start on my device
but when trying to connect it won't work and will start saying "downloading - tap to cances", whereas the app-files serving server did does not appear to react to any request.
Does this forever - when tapping - nothing happens.

Shall therefore be opened another issue?

**Comment by surajpindoria** [comment]
Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), we point out some common issues that can cause this. Scroll down to the section `PhoneGap Developer App is unable to download from the server`

**Comment by JhonnyJason** [comment]
thanx, would be the same case as the issue stated there for "PhoneGap Developer App hangs on DOWNLOADING... for iOS", just I'm on Android, so I guess it is not the same issue.

I guess I will accept for now that the Phonegap developer app is not how I may test - due to time issues on my schedule and no other device available on the fast hand.

And I guess I will research more deeply about that issue later - maybe it already has been resolved then :D 

So I close this issue because it appears to be more related to gaze, i guess.

**Comment by surajpindoria** [comment]
That section I pointed to could still lead to a possible solution and is platform agnostic. The iOS section refers to another issue where if you type in the incorrect IP address it hangs.
