### ISSUE TITLE
Why is the "browser" platform added automatically by "phonegap serve"?

### ISSUE THREAD

**Issue by ZaLiTHkA** [phonegap/phonegap-cli#733]
>Note: I'm not using the "new issue" template for this because it's not a bug report..

Just for clarification, I've been working on a mobile app for a while now, after getting sick of dealing with stupid issues in a VS2015-based project, I recently ported all our code across to a plain and simple PhoneGap project. So much simpler this way. :)

Over the past 2 days I've been working out a few kinks in the process, but one point that still doesn't make sense to me is this: every time I run `phonegap serve` on my project, the "browser" platform is re-added, but I don't see any real need for it.

Is this expected behaviour? I thought this sort of thing (i.e.: targeted platforms) was an opt-in idea, not forced on a project. Otherwise, could this be something related to the internal "serve" task, perhaps in aid of supporting live reload..?

Naturally, I would prefer this to be optional, so if it isn't explicitly required, my next request would logically be "please can we make it optional"?

**Comment by surajpindoria** [comment]
Hi @ZaLiTHkA,

This is the expected behavior. The browser platform just provides a faster way to preview the app in your desktop browser as you are developing your app. You can prevent this by adding the no browser flag, `phonegap serve --no-browser`.

**Comment by ZaLiTHkA** [comment]
Ah, I see now. I remember seeing that option in the docs, but the descriptions on that page don't say much about how it actually affects the project itself.

Is there any way to set defaults for these options in a project config file? Perhaps something like a `.phonegaprc` file of sorts?

**Comment by surajpindoria** [comment]
Unfortunately we don't have support for a project config file, but that is something we can look into on our end.

As to how it affects the project, it doesn't. The rest of your project will remain unchanged, the browser platform is only there for testing purposes and nothing else.

**Comment by ZaLiTHkA** [comment]
Yeah, sorry by "my app's runtime", I was taking specifically in the context of the `phonegap serve` command. Been a long day, apparently my brain isn't working properly at the moment.

Thanks for the clarification though, I do appreciate it. Having a project config file to set defaults for these sort of options in the development stages would be very beneficial, so I do hope you guys add that at some point. :) But for now, I'd say my question is answered.
