### ISSUE TITLE
No scroll inertia/momentum 

### ISSUE THREAD

**Issue by edvenkat** [phonegap/phonegap-cli#743]
Hai All,

No scroll inertia/momentum - when i scroll the page, the event scroll call only end of the scroll not between

please advice

```
$$('#xxx').scroll(function () {
}); 
```

**Comment by edvenkat** [comment]
I have added the code in below url

https://github.com/edvenkat/sticky-header

Please advice.

**Comment by purplecabbage** [comment]
This is not a phonegap issue.
Have a look at https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo
http://iamdustan.com/smoothscroll/
