### ISSUE TITLE
Phonegap serve not working anymore (7.1.0)

### ISSUE THREAD

**Issue by MitchellBouwman** [phonegap/phonegap-cli#746]
### PhoneGap CLI
New phonegap 7.1.0 version

### Error:
I was developing for hours today, than my "phonegap serve" stopped working and NPM suggested me to update the Phonegap CLI. I did by running the npm command.

After that I wanted to start my connection again to my phone but the command "phonegap serve" does nothing anymore. No responds, nothing.

Also I could not find what's new in 7.1.0.
Downgrading for now to 7.0.1 till this is fixed.

**Comment by surajpindoria** [comment]
I noticed this yesterday as well, I am looking into it. Thanks for reporting this @MitchellBouwman

**Comment by MitchellBouwman** [comment]
@jlchereau Yes this was on Windows 10 for me also.
@surajpindoria No problem!

**Comment by ogunm** [comment]
Im using windows 7 and i have a same problem 
Updating phonegap cli after serve command not working now
like this in cmd

`c:\xxx\ogun>phonegap serve

c:\xxx\ogun>`

not started server and no returns any error and any log

"ogun" folder my project folder
cordova serve command working succesfuly.

**Comment by martijndk** [comment]
Same problem here, fresh installation of phonegap and no response when running 'phonegap serve'.

Phonegap CLI: 7.1.0
NodeJS: v6.11.4
MacOS: 10.13

**Comment by demoncyborg0** [comment]
i got the same problem too  ... need some help to fix it

**Comment by masoodanwar85** [comment]
I got the same problem when I updated phonegap version to 7.1.0. 
To fix it, I reverted back the version to 7.0.1 and it was working fine.
There seems to be an issue with the latest version i.e. 7.1.0

**Comment by MartinHnik** [comment]
Same here, macOS High Sierra, CLI v7.1.0.

**Comment by surajpindoria** [comment]
Just released a new version that fixes this.

**Comment by MitchellBouwman** [comment]
Great work, thank you @surajpindoria!
