### ISSUE TITLE
Proxy passthrough

### ISSUE THREAD

**Issue by heruan** [phonegap/phonegap-cli#75]
How can I use the phonegap cli behind a proxy? It fails when downloading assets.

**Comment by kholy87** [comment]
Has anyone had any luck in getting phonegap-cli to work with proxy? I need this functionality but I am behind a company proxy. 

Thanks!

**Comment by mwbrooks** [comment]
@kholy87 Could you provide an example of the command that you are running? The PhoneGap CLI tries to inherit from npm's proxy settings, but depending on the command, you may need to update your git configuration as well.

**Comment by kholy87** [comment]
I am just trying to login. When I type the remote login I get a ETIMEDOUT because of the proxy. I have tried adding --proxy

**Comment by surajpindoria** [comment]
@kholy87 

What version of the CLI are you using? We changed some parameters around recently and there was a couple of releases where it was messed up for build. Should be good in the latest.

**Comment by kholy87** [comment]
@surajpindoria 6.3.3

**Comment by surajpindoria** [comment]
@kholy87 

I believe you should be able to pass the proxy as an option in the CLI, 
`phonegap remote login --proxy http://myproxy.com`.

It may or may not require quotes around the URL, I have not tried this myself before.

**Comment by purplecabbage** [comment]
Assumed to be fixed.
