### ISSUE TITLE
serve "Project already exists" on 7.1.1

### ISSUE THREAD

**Issue by samlittler** [phonegap/phonegap-cli#754]
### PhoneGap CLI, node & npm versions

Phonegap: 7.1.1
nodejs: v4.2.6
npm: 5.3.0

### Expected Behaviour

App is served with no errors

### Actual Behaviour

The first time `phonegap serve` is run on a project, phonegap creates a "serve" directory in the project directory and runs it. After stopping the server and running `phonegap serve` a error message stating "Project already exists! Delete and recreate" appears.

### Steps to Reproduce 

I cloned a project from git (which I can't share unfortunately), but it seems to happen on any app template.

1. Clone repository from git. My repo contains the follow files/folders. The rest are gitignored.

- www
- .bithoundrc
- .bowerrc
- .gitignore
- bower.json
- config.xml
- package-lock.json

2. cd in the project folder

3. `phonegap serve`

    *Phonegap creates a "serve" directory in my project that contains a demo app with index.html etc.

4. Ctrl+C to cancel

5. `phonegap serve`

    *Error is displayed*

#### Error messages

"Project already exists! Delete and recreate"

#### Furthermore

This error does not occur on 7.0.1. Some behaviour has been changed (as is expected between minor versions). I've rolled-back until this is resolved or someone can explain what I'm doing wrong XD.

**Comment by surajpindoria** [comment]
Hi @samlittler,

Just tried this myself using version 7.1.1 and am not able to reproduce this error. There is no "serve" directory and I am able to run the command multiple times consecutively. Can you try completely uninstalling phonegap, `npm uninstall -g phonegap`, and reinstalling, `npm install -g phonegap`. Maybe there is something that's gone wrong with your install.

**Comment by samlittler** [comment]
Hi @surajpindoria,

Thanks for your aid in this. I tried that to no avail I'm afraid. Please see the output from my command line attached.

`samlittler@samlittler-p6-2302eam:~/phonegap$ ll
total 8
drwxrwxr-x  2 samlittler samlittler 4096 Dec 15 09:18 ./
drwxr-xr-x 53 samlittler samlittler 4096 Dec 13 11:43 ../
samlittler@samlittler-p6-2302eam:~/phonegap$ sudo npm uninstall -g phonegap
removed 907 packages in 7.176s
samlittler@samlittler-p6-2302eam:~/phonegap$ sudo npm install -g phonegap
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/phonegap -> /usr/local/lib/node_modules/phonegap/bin/phonegap.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/phonegap/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ phonegap@7.1.1
added 1023 packages in 18.042s
samlittler@samlittler-p6-2302eam:~/phonegap$ git clone git@github.com:REDACTED/REDACTED
Cloning into 'REDACTED'...
remote: Counting objects: 834, done.
remote: Compressing objects: 100% (552/552), done.
remote: Total 834 (delta 290), reused 783 (delta 239), pack-reused 0
Receiving objects: 100% (834/834), 4.88 MiB | 1.96 MiB/s, done.
Resolving deltas: 100% (290/290), done.
Checking connectivity... done.
samlittler@samlittler-p6-2302eam:~/phonegap$ cd REDACTED/
samlittler@samlittler-p6-2302eam:~/phonegap/REDACTED$ phonegap serve
Creating Browser project. Path: serve
[phonegap] starting app server...
[phonegap] listening on 10.0.0.192:3000
[phonegap] 
[phonegap] ctrl-c to stop the server
[phonegap] 
[VARIOUS PROJECT FILES REDACTED]
[phonegap] 200 /plugins/org.apache.cordova.file/www/DirectoryEntry.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/DirectoryReader.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/Entry.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/File.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/FileEntry.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/FileError.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/FileReader.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/FileSystem.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/FileUploadOptions.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/FileUploadResult.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/FileWriter.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/Flags.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/LocalFileSystem.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/Metadata.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/ProgressEvent.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/fileSystems.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/requestFileSystem.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/resolveLocalFileSystemURI.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/ios/FileSystem.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/fileSystems-roots.js
[phonegap] 200 /plugins/org.apache.cordova.file/www/fileSystemPaths.js
[phonegap] 200 /plugins/org.apache.cordova.file-transfer/www/FileTransferError.js
[phonegap] 200 /plugins/org.apache.cordova.file-transfer/www/FileTransfer.js
[phonegap] 200 /plugins/org.apache.cordova.geolocation/www/Coordinates.js
[phonegap] 200 /plugins/org.apache.cordova.geolocation/www/PositionError.js
[phonegap] 200 /plugins/org.apache.cordova.geolocation/www/Position.js
[phonegap] 200 /plugins/org.apache.cordova.geolocation/www/geolocation.js
[phonegap] 200 /plugins/org.apache.cordova.globalization/www/GlobalizationError.js
[phonegap] 200 /plugins/org.apache.cordova.globalization/www/globalization.js
[phonegap] 200 /plugins/org.apache.cordova.inappbrowser/www/inappbrowser.js
[phonegap] 200 /plugins/org.apache.cordova.media/www/MediaError.js
[phonegap] 200 /plugins/org.apache.cordova.media/www/Media.js
[phonegap] 200 /plugins/org.apache.cordova.media-capture/www/CaptureAudioOptions.js
[phonegap] 200 /plugins/org.apache.cordova.media-capture/www/CaptureImageOptions.js
[phonegap] 200 /plugins/org.apache.cordova.media-capture/www/CaptureVideoOptions.js
[phonegap] 200 /plugins/org.apache.cordova.media-capture/www/CaptureError.js
[phonegap] 200 /plugins/org.apache.cordova.media-capture/www/MediaFileData.js
[phonegap] 200 /plugins/org.apache.cordova.media-capture/www/MediaFile.js
[phonegap] 200 /plugins/org.apache.cordova.media-capture/www/capture.js
[phonegap] 200 /plugins/org.apache.cordova.network-information/www/network.js
[phonegap] 200 /plugins/org.apache.cordova.network-information/www/Connection.js
[phonegap] 200 /plugins/org.apache.cordova.splashscreen/www/splashscreen.js
[phonegap] 200 /plugins/org.apache.cordova.statusbar/www/statusbar.js
[phonegap] 200 /plugins/org.apache.cordova.vibration/www/vibration.js
[phonegap] 200 /plugins/org.apache.cordova.battery-status/www/battery.js
[phonegap] 200 /plugins/org.apache.cordova.camera/www/CameraConstants.js
[phonegap] 200 /plugins/org.apache.cordova.camera/www/CameraPopoverOptions.js
[phonegap] 200 /plugins/org.apache.cordova.camera/www/Camera.js
[phonegap] 200 /plugins/org.apache.cordova.camera/www/ios/CameraPopoverHandle.js
[phonegap] 200 /plugins/org.apache.cordova.console/www/console-via-logger.js
[phonegap] 200 /plugins/org.apache.cordova.console/www/logger.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/contacts.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/Contact.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/ContactAddress.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/ContactError.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/ContactField.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/ContactFindOptions.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/ContactName.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/ContactOrganization.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/ContactFieldType.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/ios/contacts.js
[phonegap] 200 /plugins/org.apache.cordova.contacts/www/ios/Contact.js
[phonegap] 200 /plugins/org.apache.cordova.device/www/device.js
[phonegap] 200 /plugins/org.apache.cordova.device-motion/www/Acceleration.js
[phonegap] 200 /plugins/org.apache.cordova.device-motion/www/accelerometer.js
[phonegap] 200 /plugins/org.apache.cordova.device-orientation/www/CompassError.js
[phonegap] 200 /plugins/org.apache.cordova.device-orientation/www/CompassHeading.js
[phonegap] 200 /plugins/org.apache.cordova.device-orientation/www/compass.js
[phonegap] 200 /plugins/org.apache.cordova.dialogs/www/notification.js
[phonegap] 200 /plugins/nl.x-services.plugins.insomnia/www/Insomnia.js
[phonegap] 200 /plugins/ADBMobile/sdks/Cordova/ADBMobile/Shared/ADBHelper.js
[phonegap] 404 /ServiceWorker.js
Using cordova-fetch for cordova-browser@~4.1.0


Adding browser project...


Creating Browser project. Path: platform

Unable to load PlatformApi from platform. Error: Unhandled "error" event. (Does not appear to implement platform Api.)

Error: Unhandled "error" event. (The platform "browser" does not appear to be a valid cordova platform. It is missing API.js. browser not supported.)


Project already exists! Delete and recreate
samlittler@samlittler-p6-2302eam:~/phonegap/REDACTED$ 
samlittler@samlittler-p6-2302eam:~/phonegap/REDACTED$ ll
total 88
drwxrwxr-x 9 samlittler samlittler  4096 Dec 15 09:20 ./
drwxrwxr-x 3 samlittler samlittler  4096 Dec 15 09:20 ../
-rw-rw-r-- 1 samlittler samlittler  1229 Dec 15 09:20 .bithoundrc
-rw-rw-r-- 1 samlittler samlittler   816 Dec 15 09:20 bower.json
-rw-rw-r-- 1 samlittler samlittler    34 Dec 15 09:20 .bowerrc
-rw-rw-r-- 1 samlittler samlittler  8140 Dec 15 09:20 config.xml
drwxrwxr-x 8 samlittler samlittler  4096 Dec 15 09:20 .git/
-rw-rw-r-- 1 samlittler samlittler   117 Dec 15 09:20 .gitignore
drwxrwxr-x 2 samlittler samlittler  4096 Dec 15 09:20 hooks/
drwxrwxr-x 3 samlittler samlittler  4096 Dec 15 09:20 node_modules/
-rw-rw-r-- 1 samlittler samlittler   214 Dec 15 09:20 package.json
-rw-rw-r-- 1 samlittler samlittler 23200 Dec 15 09:20 package-lock.json
drwxrwxr-x 9 samlittler samlittler  4096 Dec 15 09:20 platform/
drwxrwxr-x 2 samlittler samlittler  4096 Dec 15 09:20 platforms/
drwxrwxr-x 9 samlittler samlittler  4096 Dec 15 09:20 serve/
drwxrwxr-x 9 samlittler samlittler  4096 Dec 15 09:20 www/
samlittler@samlittler-p6-2302eam:~/phonegap/REDACTED$ `

On this occasion, I couldn't get phonegap to serve the *first* time.

**Comment by surajpindoria** [comment]
Looks it is downloading an old version of the browser platform which is causing some issues. Can you remove that, `phonegap platform rm browser`, and then try to serve again.

**Comment by samlittler** [comment]
@surajpindoria Excellent, that seems to have resolved it!

**Comment by surajpindoria** [comment]
@samlittler,

Nice, glad you got it working!
