### ISSUE TITLE
cordova_plugins.js Error 404 in browser, after creating from template

### ISSUE THREAD

**Issue by uglycoyote** [phonegap/phonegap-cli#762]
### PhoneGap CLI, node & npm versions

```
➜  phonegap -v
7.1.1
➜  npm -v
5.6.0
➜  node -v
v8.9.1
```

### Expected Behaviour

Example templates should work without errors.

### Actual Behaviour

Example templates cause browser to try to access ```cordova_plugins.js``` and give error 404.

### Steps to Reproduce 

```
phonegap create test --template blank
cd test
phonegap run browser
```

open Chrome developer tools,   I get ```cordova.js:1534 GET http://localhost:8000/cordova_plugins.js net::ERR_ABORTED``` in console.

(I also ran into the same issue on the Framework7 template)

#### Sample Code that illustrates the problem

No code necessary, templates exhibit problem.

#### Error messages

```cordova.js:1534 GET http://localhost:8000/cordova_plugins.js net::ERR_ABORTED```

**Comment by surajpindoria** [comment]
Hi @uglycoyote,

This is actually expected as the blank template does not include any plugins, therefore it doesn't have a `cordova_plugins.js` file yet. Once you add plugins to your project it will generate this file for you.

**Comment by uglycoyote** [comment]
Errors are not expected with a sample "getting started" project.  I generally assume that if I get an error there is something wrong.   

If plugins are required in order for the template to function error free then perhaps the template should include plugins?   Is it not valid to have a project which does not use plugins?

**Comment by purplecabbage** [comment]
This is not an error.

**Comment by uglycoyote** [comment]
At the time I was writing this issue I had just freshly made a phonegap app from the template and was having difficulty getting it to work.  I opened developer tools and saw red and the word ERR.  So regardless of whether you consider this particular ERR to be an actual error, I can say that it doesn't make for a very good first impression when things don't run cleanly out of the box, and it causes frustration when trying to troubleshoot something when there are a bunch of ERR's that are "to be expected", irrelevant, or non-fatal.

**Comment by purplecabbage** [comment]
I agree it is not ideal, and appreciate your persistence. However this is something that lives deep in cordova code, and needs to be handled there.

**Comment by uglycoyote** [comment]
Should I add this issue on the apache/cordova github repo then?
