### ISSUE TITLE
stop the auto load

### ISSUE THREAD

**Issue by Crisium** [phonegap/phonegap-cli#765]

**Comment by Crisium** [comment]
there is no option to turn off the auto load with the gui

**Comment by maverickmishra** [comment]
Please follow the [Issue Template](https://github.com/phonegap/phonegap-cli/blob/master/.github/ISSUE_TEMPLATE.md) to explain this issue clearly.

**Comment by Crisium** [comment]
omg what do  you not understand!?!?!
"there is no option to turn off the auto load with the gui" 

@maverickmishra read read read

**Comment by purplecabbage** [comment]
@crisium This is a command line tool, there is no gui ... explain explain explain ...
You probably meant the desktop app.
This has been on the backlog for a long time, so it is doubtful to happen soon, but you could go and post a comment there.
https://github.com/phonegap/phonegap-app-desktop/issues/255
