### ISSUE TITLE
[ERROR] Error initializing Cordova: Missing Command Error

### ISSUE THREAD

**Issue by turnipjs** [phonegap/phonegap-cli#770]
### PhoneGap CLI, node & npm versions
Phonegap: 8.0.0  
npm: 5.7.1  
node: 9.0.0  

### Expected Behaviour
No error  

### Actual Behaviour
Popup in browser (chrome v64.0.3282.186) when I load my project (no plugins).  
Popup says: [ERROR] Error initializing Cordova: Missing Command Error  

### Steps to Reproduce 
Unsure, it just started doing it one day.  

#### Sample Code that illustrates the problem
May or may not happen for you, but the project is at [http://github.com/turnipjs/ScratchPadGroceryList](http://github.com/turnipjs/ScratchPadGroceryList).  

#### Error messages
Popup says: [ERROR] Error initializing Cordova: Missing Command Error  
  
  
Note that this is not a critical error, just an annoying popup every time the page is refreshed and does not show up on mobile in either builds or the Phonegap app.

**Comment by imjeffparedes** [comment]
Same here

**PhoneGap CLI, node & npm versions**
Phonegap: 8.0.0
npm: 5.6.0
node: 9.7.0

**Error messages**
Console error:
[ERROR] Error initializing Cordova: Missing Command Error

**Result**
White screen on browser and android build

**Comment by krampstudio** [comment]
On my hand it looks like this occur only when I start `phonegap serve` with Chromium already opened on my app (waiting for a re-connecrt) and having the DevTools already opened. 
If I close the DevTools, and restart the server, everything is fine...

**Comment by purplecabbage** [comment]
As @krampstudio points out, this is an issue with trying to reuse a connection that no longer exists.
Close the browser tab before re-running serve.

**Comment by imjeffparedes** [comment]
@purplecabbage @krampstudio didn't work for me.

**Comment by Shaedo** [comment]
This is also happening to me. I can reproduce this by selecting [Clear site data]  found under Clear storage as well as the situation described by [krampstudio]
