### ISSUE TITLE
Adding/Removing platforms fail when index.html is read-only (on Windows 10)

### ISSUE THREAD

**Issue by jlchereau** [phonegap/phonegap-cli#772]
### PhoneGap CLI, node & npm versions

v8

### Expected Behaviour

`phonegap platforms add [android|ios|windows]` should work if index.html has attribute R = read-only on Windows (maybe on other platforms too).

### Actual Behaviour

```
D:\path>phonegap platforms add windows@6
Using cordova-fetch for cordova-windows@6


Adding windows project...


Creating Cordova Windows Project:

        Path: platforms\windows
        Namespace: com.example.mobile
        Name: Mobile app

Windows project created with cordova-windows@6.0.0

(node:6248) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, open 'D:\path\platforms\windows\www\index.html'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at addBOMToFile (D:\path\platforms\windows\cordova\lib\prepare.js:686:12)
    at Array.forEach (<anonymous>)
    at addBOMSignature (D:\path\platforms\windows\cordova\lib\prepare.js:665:1
0)
    at D:\path\platforms\windows\cordova\lib\prepare.js:625:13
    at _fulfilled (D:\path\platforms\windows\cordova\node_modules\q\q.js:854:5
4)
    at self.promiseDispatch.done (D:\path\platforms\windows\cordova\node_modul
es\q\q.js:883:30)
    at Promise.promise.promiseDispatch (D:\path\platforms\windows\cordova\node
_modules\q\q.js:816:13)
    at D:\path\platforms\windows\cordova\node_modules\q\q.js:624:44

(node:6248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either b
y throwing inside of an async function without a catch block, or by rejecting a promise which was not han
dled with .catch(). (rejection id: 1)
(node:6248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, pro
mise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Steps to Reproduce 

Mark index.html as read-only and add platform a in the log above.

*Note: The issue also occurs with adding plugins and with other files marked as read-only, like any js file referenced by index.html.*

**Comment by purplecabbage** [comment]
In what circumstance does this happen to you? Why do you need www/index.html to be readonly?
This does not seem like an issue to me ... there are literally hundreds of things you could do to index.html that would end up breaking the tooling.

**Comment by jlchereau** [comment]
From a pure development perspective, I do not see why adding a platform would require RW access to user files including index.html in a phonegap/cordova project. This is just lazy coding.

From a user perspective, we have variations of the same app and our procedures mark files that are not supposed to be changed in a variation as read-only. This ensures that files are modified where they should be and changes be propagated appropriately to all variations.

**Comment by purplecabbage** [comment]
Anything inside platforms/ is generally considered build cruft, developers should not be changing platforms/windows/www/index.html themselves.
Windows app store submissions have strict requirements on the files in a js app submission.
HTML, CSS, and JavaScript files must be encoded in UTF-8 form with a corresponding byte-order mark (BOM) to benefit from bytecode caching and avoid certain runtime error conditions.
https://docs.microsoft.com/en-us/previous-versions/windows/apps/jj657973(v=win.10)

**Comment by jlchereau** [comment]
We are not changing anything inside `platforms/windows/www/index.html`. We are setting `www/index.html` as read-only and phonegap propagates the R attribute when copying our files to platforms\windows.

**Comment by purplecabbage** [comment]
Got that part.  Is it possible to use git to track file changes, or some other system?

I have created an issue here: https://issues.apache.org/jira/browse/CB-13991
This is firmly a cordova issue and not a phonegap specific issue.

**Comment by jlchereau** [comment]
We are using git, but git does not prevent changes.

Note that some VCS mark files as read-only. In the old days, this is the way Visual SourceSafe and Team Foundation Server locked checked-in files and a user checkout would remove the R attribute.

**Comment by purplecabbage** [comment]
This behavior is deeply embedded in apache cordova platform add code, unfortunately it would take considerable re-architecting.
