### ISSUE TITLE
Inputs type text don't work on iOS

### ISSUE THREAD

**Issue by JasonGlez** [phonegap/phonegap-cli#778]
### PhoneGap CLI, node & npm versions
PhoneGap CLI Version: 8.0.0
Xcode Version: 9.3
Node Version: 8.11.1 
NPM Version: 5.8.0
Git Version: 2.16.3
ios-sim Version: 6.1.2

Using the following preferences in config.xml all the inputs type "text" stop working and cannot be clickable.
```
<preference name="SuppressesLongPressGesture" value="true" />
<preference name="Suppresses3DTouchGesture" value="true" />
```
Devices tested:
- iPhone X 11.3 (Emulator)
- iPhone 6 10.2.1 (physical device)
### Expected Behaviour
- The inputs are clickable and the user can write.
### Actual Behaviour
- The inputs are not clickable and the user cannot write
- Note: Sometimes the application opens the keyboard, but it's really difficult to get.
### Steps to Reproduce 
- Create a new project: phonegap create myApp
- Add some inputs type text in the HTML
- Run the application: phonegap run ios

**Comment by JasonGlez** [comment]
Check the following thread for more information:
https://issues.apache.org/jira/browse/CB-14039?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by purplecabbage** [comment]
This was a cordova-ios issue, it was addressed here: https://github.com/apache/cordova-ios/pull/364
