### ISSUE TITLE
Ajax iOS is not working

### ISSUE THREAD

**Issue by syahnur197** [phonegap/phonegap-cli#781]
I use PhoneGap Build to build my app remotely. I use AjaxForm, it works well on Android App that built from Phonegap Build. But the same AJAX function did not work on the iOS app.

This is my config.xml

    <?xml version='1.0' encoding='utf-8'?>
    <widget id="com.com.com" version="1.3.0" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:gap="http://phonegap.com/ns/1.0">
        <name>name</name>
        <description>
            description
        </description>
        <author email="support@phonegap.com" href="http://phonegap.com">
            MyName
        </author>       
        <access origin="*" />
        <access launch-external="yes" origin="tel:*" />
        <allow-navigation href="http://*/*" />
        <allow-navigation href="https://*/*" />
        <allow-navigation href="data:*" />
        <access minimum-tls-version="TLSv1.1" origin="*" requires-certificate-transparency="true" requires-forward-secrecy="false" />
        <platform name="android">
            <allow-intent href="market:*" />
        </platform>
        <platform name="ios">
            <allow-intent href="market:*" />
            <allow-navigation href="http://*/*" />
            <allow-navigation href="https://*/*" />
            <allow-navigation href="data:*" />
            <allow-intent href="*" />
            <allow-navigation href="*" />
            <allow-intent href="tel:*" />
            <allow-intent href="sms:*" />
            <allow-intent href="mailto:*" />
            <allow-intent href="geo:*" />
        </platform>
        <engine name="android" spec="~7.0.0" />
        <engine name="ios" spec="^4.5.4" />
    </widget>
I have tried several solutions that I found in StackOverflow but all of them didn't work. Even normal JS function didn't work. I tried to alert() a string right after document ready function, the alert does not work at all. I tried bringing all my scripts from the <body> tag into the <head> but it didn't have any effect.

I also tried to add

 <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"/>
right after the opening <head> tag in my index.html, but still no result. Most of the solutions I found on the web is outdated.

Please helps thanks

**Comment by purplecabbage** [comment]
There is not enough info here to tell what is happening.  
Can you prepare a brief example app to share, simply demonstrating the issue and nothing more.  
Closing for now, please re-open when you have more data.
