### ISSUE TITLE
Where can I find Phonegap.plist or Cordova.plist for ExternalHosts setting?

### ISSUE THREAD

**Issue by treeternity** [phonegap/phonegap-cli#789]
### PhoneGap CLI, node & npm versions
Latest
### Expected Behaviour
Where can I find Phonegap.plist or Cordova.plist for ExternalHosts setting?
### Actual Behaviour
Unsure
### Steps to Reproduce 
Created PhoneGap app using the cli but cannot find the .plist file?

**Comment by purplecabbage** [comment]
If you add the iOS platform, you can find the plist in `{app-root}/platforms/ios`
`phonegap platform add ios`
Please keep in mind that this might get overwritten by builds and might not be what you are looking for.
