### ISSUE TITLE
Error program default HelloWorld with push plugin Phonegap CLI

### ISSUE THREAD

**Issue by r4-2017** [phonegap/phonegap-cli#793]
### PhoneGap CLI, node & npm versions
Phonegap 8.0.0; npm 5.6.0; node v8.11.4

### Expected Behaviour
send of notification with push plugin to the paired Android device
### Actual Behaviour
return error message; the notification is not send

### Steps to Reproduce 
1- run phonegap serve to obtain the ip for pairing of device;
2- with pairing, get the deviceID;
3- with deviceID, run command line:  phonegap push --deviceID dHHf2P72NT0:APA91bHmh4TzmJLkdu --service fcm --payload "{ \"data\": { \"title\": \"Hello\", \"message\": \"World\"} }"

#### Sample Code that illustrates the problem
as explained above

#### Error messages
There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
Error: getaddrinfo ENOTFOUND push.api.phonegap.com push.api.phonegap.com:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

**Comment by purplecabbage** [comment]
Unfortunately the push service has been shut down, which means you will need to roll much of this yourself.
The cli will have the push command removed soon, and do a better job of letting you know that it won't work.
