### ISSUE TITLE
Remove push command integration

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/phonegap-cli#794]
With the push service shut down, we need to output helpful text to users expecting it to still work via the cli.

**Comment by littleowlnest** [comment]
The "push service shut down"... is this what results in this message?

There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
Error: getaddrinfo ENOTFOUND push.api.phonegap.com push.api.phonegap.com:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)

**Comment by purplecabbage** [comment]
Yes @littleowlnest this is the issue you ran into.
The latest published version (v8.2.1) has removed the push command, and help text does not display it as an available command.
