### ISSUE TITLE
Very minor command output notification issue

### ISSUE THREAD

**Issue by Aggror** [phonegap/phonegap-cli#798]
### PhoneGap CLI, node & npm versions
CLI 8.2.1

### Expected Behaviour
Very minor issue, but the CLI (8.0.0) normally says something like 
```
[Phonegap] Compressing
[Phonegap] Uploading 
[Phonegap] Building 
```

### Actual Behaviour
Since updating to 8.2.1 I see
```
undefined Compressing
undefined Uploading 
undefined Building 
```

### Steps to Reproduce 
Use any command in the CLI 8.2.1 in powershell.

**Comment by purplecabbage** [comment]
Install 8.2.2
