### ISSUE TITLE
Failure to compress app for upload could be clearer

### ISSUE THREAD

**Issue by bemjb** [phonegap/phonegap-cli#80]
I just attempted to do a remote build, and it failed with the following error:

  phonegap  compressing the app...
     error  failed to create the zip file: /home/bemjb/Dropbox/mobile/timergap/build/www.zip

Turns out that I just didn't have 'zip' installed, but I think it would be helpful if this gave more information. Perhaps in the situation where it can't run zip, it says something like "Failed to run the 'zip' command, do you have it installed?', (Ideally, it would differentiate between not being able to run it and not being able to find it, but that's just gravy. :-). Also, perhaps messages for other failures, like not having enough disk space for the zip file to be created.

**Comment by webdude-75** [comment]
I am getting the following error in the CLI: 

[phonegap] compressing the app...
   [error] failed to create the zip file: 'wscript' is not recognized as an internal or external command,
   [error] operable program or batch file.
   [error]
(node:18020) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

I have tried everything from uninstalling and reinstalling different versions of nodejs, phonegap and npm.

Is there a fix for this?
