### ISSUE TITLE
Unable to add phonegap 8.2.2

### ISSUE THREAD

**Issue by FreddyCrugger** [phonegap/phonegap-cli#804]
Hello,

I am having a problem on windows 10.

**Problem 1**
I am unable to uninstall phonegap, when running his command:
`npm uninstall --global phonegap`

And then running this command:
phonegap -v

I am still seeing phonegap v7.1.1

The uninstall command does not work.

**Problem 2:**
I am unable to install phonegap 8.2.2, whatever I do the version 7.1.1 shows up all the time.
I tried:
`npm install -g phonegap@latest`
and
`npm install -g phonegap@8.2.2`

**Comment by wbochar** [comment]
I have the same issue, Windows 10 but with version 8 - > 8.2.2

**Comment by FreddyCrugger** [comment]
I gave up on Phonegap, instead simply use Cordova, no more problems.
I find no differences between Cordova and Phonegap, same commands.
All you have to do is generate your apps via command lines, that's all.

**Comment by tamb** [comment]
> 
> 
> I gave up on Phonegap, instead simply use Cordova, no more problems.
> I find no differences between Cordova and Phonegap, same commands.
> All you have to do is generate your apps via command lines, that's all.

There's a difference between `phonegap serve` and `cordova serve`.  Phonegap really helps with hot reloading.  Super useful when testing plugins.

**Comment by FreddyCrugger** [comment]
if you use vue it will hot reload with the cli3 automatically with the new vue ui

**Comment by purplecabbage** [comment]
Can you run `which phonegap` and report back the output?
Also, what windows terminal are you using?  I recommend the git-bash terminal as it is identical to bash terminal on mac/linux

**Comment by FreddyCrugger** [comment]
Sorry but this is a very old thread(January 24th). I have moved on since and dropped Phonegap.
Thank you.

**Comment by purplecabbage** [comment]
sorry to hear that
