### ISSUE TITLE
Unable to install phonegap CLI 

### ISSUE THREAD

**Issue by MicheleVario85** [phonegap/phonegap-cli#828]
### PhoneGap: 9.0.0, node: 12.16.2, npm: 6.14.4

Hi, 
after launching $ npm install -g phonegap as written in https://phonegap.com/getstarted/
I'm getting the following string:

> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> /Users/myusernmane/.npm-global/bin/phonegap -> /Users/myusername/.npm-global/lib/node_modules/phonegap/bin/phonegap.js
> npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"12.16.2","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: got@5.7.1
> 
> + phonegap@9.0.0
> updated 1 package in 21.346s

is there any solution?

**Comment by gplusdotgr** [comment]
@MicheleVario85 it is asking for your node to be from 0.10 to 7, and if you run `node -v` you'll see you're running `12.16.1`. 
Why are you trying to install version 0.0.9 of PhoneGap when the latest version is 9.0.0? https://github.com/phonegap/phonegap-cli/releases 
If you need to have multiple versions of `node` in your system, you need to use something like https://github.com/tj/n or https://github.com/nvm-sh/nvm .

**Comment by MicheleVario85** [comment]
> Why are you trying to install version 0.0.9 of PhoneGap when the latest version is 9.0.0?

Sorry, my mistake, i'm trying to install the latest version of Phonegap.  Just edited the title.

> If you need to have multiple versions of `node` in your system, you need to use something like https://github.com/tj/n or https://github.com/nvm-sh/nvm .

Thanks for your help, i'll trying as your suggestion.

**Comment by MicheleVario85** [comment]
Solved.
The problem was not the version of npm but in npm prefix. 
So first "$ npm config set prefix /usr/local" then install phonegap with "$ npm install -g phonegap".
Hope this can be helpful for someone else.

**Comment by oniko94** [comment]
I'm having the same issue on Windows 10.

Running: `PS C:\Users\me> npm i -g phonegap`

Output:

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
C:\Users\me\AppData\Roaming\npm\phonegap -> C:\Users\me\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\phonegap\node_modules\chokidar\node_modules\fsevents):
npm WARN SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"12.16.3","npm":"6.14.4"})
npm WARN Not compatible with your version of node/npm: got@5.7.1
```

**Comment by chrisgriffith** [comment]
You should actually use the Cordova CLI instead. The Phonegap CLI was a fork of it to enable integration with PhoneGap Build. Adobe is no longer supporting PhoneGap or PhoneGap Build.
