### ISSUE TITLE
phonegap run ios --device launches on simulator

### ISSUE THREAD

**Issue by patramsey** [phonegap/phonegap-cli#94]
# Overview

phonegap run ios --device launches on ios simulator rather than device when device is plugged in. 
### Steps to Reproduce

``` javascript
phonegap create testapp
cd test
phonegap run ios --device
```
- os x version 10.8.4
- xcode 4.6.3
- ios version 6.1.4
- ios-sim version 1.7

**Comment by JesseScott** [comment]
I am seeing this behaviour resurface... 

*Cordova: 4.3.0* 
*iOS Platform: 3.8.0*

I have a fully provisioned device, etc.
I can go into the Xcode project and run from there, but even if I close that with the target set to a device rather than the emulator, it stills deploys to the sumulator...

**Comment by shazron** [comment]
You mean the cordova-cli. phonegap-cli does not have a 4.3.0 reversion released, thus is the wrong issue tracker for this.

In any case I just ran `cordova run ios --device` in  a new project, it deployed to device correctly. Make sure you have iso-deploy 1.4.0 installed as well, if not it errors out.

**Comment by MakeHui** [comment]
@shazron Thank, just as you have said
